
:- discontiguous is_/2.
:- discontiguous disjoi_/2.

disj_(air, area).
disj_(air, ball).
disj_(air, dog).
disj_(air, man).
disj_(air, person).
disj_(area, dog).
disj_(area, man).
disj_(area, wood).
disj_(arm, girl).
disj_(baby, woman).
disj_(background, man).
disj_(background, rock).
disj_(ball, child).
disj_(ball, dog).
disj_(ball, field).
disj_(ball, football).
disj_(ball, goal).
disj_(ball, grass).
disj_(ball, man).
disj_(ball, mouth).
disj_(ball, player).
disj_(ball, potato).
disj_(ball, soccer).
disj_(ball, tennis).
disj_(banana, man).
disj_(banana, person).
disj_(band, instrument).
disj_(beach, bikini).
disj_(beach, boy).
disj_(beach, dog).
disj_(beach, girl).
disj_(beach, man).
disj_(beach, ocean).
disj_(beach, person).
disj_(beach, 't-shirt').
disj_(beach, water).
disj_(beach, woman).
disj_(bench, man).
disj_(bench, park).
disj_(bench, person).
disj_(bench, woman).
disj_(bicycle, helmet).
disj_(bicycle, man).
disj_(bicycle, person).
disj_(bicycle, trick).
disj_(bicycle, woman).
disj_(bike, biker).
disj_(bike, boy).
disj_(bike, dirt).
disj_(bike, girl).
disj_(bike, man).
disj_(bike, motocross).
disj_(bike, pants).
disj_(bike, person).
disj_(biker, dirt).
disj_(bike, rider).
disj_(bike, uniform).
disj_(bike, woman).
disj_(bikini, woman).
disj_(bird, water).
disj_(blue, girl).
disj_(blue, woman).
disj_(bmx, man).
disj_(board, man).
disj_(boat, man).
disj_(body, water).
disj_(bowl, egg).
disj_(bowl, ingredient).
disj_(bowl, lady).
disj_(bowl, man).
disj_(bowl, person).
disj_(bowl, woman).
disj_(boxing, glove).
disj_(boxing, kick).
disj_(boxing, man).
disj_(boxing, practitioner).
disj_(box, man).
disj_(boy, building).
disj_(boy, calendar).
disj_(boy, camera).
disj_(boy, coat).
disj_(boy, costume).
disj_(boy, front).
disj_(boy, game).
disj_(boy, girl).
disj_(boy, grass).
disj_(boy, guitar).
disj_(boy, hat).
disj_(boy, hill).
disj_(boy, knee).
disj_(boy, mud).
disj_(boy, ocean).
disj_(boy, outdoors).
disj_(boy, park).
disj_(boy, piano).
disj_(boy, pitcher).
disj_(boy, rock).
disj_(boy, rope).
disj_(boy, shirt).
disj_(boy, shorts).
disj_(boy, snow).
disj_(boy, soccer).
disj_(boy, tongue).
disj_(boy, 't-shirt').
disj_(boy, umbrella).
disj_(boy, wall).
disj_(boy, water).
disj_(boy, woman).
disj_(branch, dog).
disj_(branch, field).
disj_(bread, man).
disj_(bread, woman).
disj_(bridge, person).
disj_(bridge, river).
disj_(bridge, rope).
disj_(broccoli, woman).
disj_(building, front).
disj_(building, man).
disj_(building, person).
disj_(butter, man).
disj_(camera, fire).
disj_(camera, girl).
disj_(camera, group).
disj_(camera, man).
disj_(camera, person).
disj_(camera, tongue).
disj_(camera, torch).
disj_(candle, dim).
disj_(candle, group).
disj_(candle, man).
disj_(candle, person).
disj_(candle, room).
disj_(candle, table).
disj_(candle, woman).
disj_(car, child).
disj_(car, driver).
disj_(car, garage).
disj_(car, girl).
disj_(car, hand).
disj_(car, man).
disj_(car, person).
disj_(car, race).
disj_(carrot, floor).
disj_(carrot, guinea).
disj_(carrot, man).
disj_(carrot, onion).
disj_(carrot, piece).
disj_(carrot, pig).
disj_(carrot, pork).
disj_(carrot, woman).
disj_(car, sky).
disj_(car, street).
disj_(car, suitcase).
disj_(cart, man).
disj_(car, toy).
disj_(car, track).
disj_(car, trunk).
disj_(car, woman).
disj_(cat, dog).
disj_(cat, milk).
disj_(cat, person).
disj_(cat, watermelon).
disj_(chair, man).
disj_(cheese, man).
disj_(child, coat).
disj_(child, family).
disj_(child, father).
disj_(child, grass).
disj_(child, group).
disj_(child, house).
disj_(child, jeans).
disj_(child, lady).
disj_(child, man).
disj_(child, outdoors).
disj_(child, park).
disj_(child, pool).
disj_(child, school).
disj_(child, snow).
disj_(child, step).
disj_(child, stone).
disj_(child, street).
disj_(child, toy).
disj_(child, water).
disj_(child, woman).
disj_(chop, pork).
disj_(chop, woman).
disj_(city, man).
disj_(city, person).
disj_(city, woman).
disj_(cliff, man).
disj_(cliff, person).
disj_(cliff, rope).
disj_(clothing, woman).
disj_(coat, dog).
disj_(coat, father).
disj_(coat, umbrella).
disj_(competition, man).
disj_(container, man).
disj_(container, plastic).
disj_(cosmetic, eye).
disj_(cosmetic, eyelid).
disj_(cosmetic, woman).
disj_(costume, person).
disj_(costume, woman).
disj_(country, dog).
disj_(country, shade).
disj_(country, tree).
disj_(cowboy, horse).
disj_(crowd, front).
disj_(crowd, woman).
disj_(daughter, father).
disj_(dim, group).
disj_(dim, man).
disj_(dim, person).
disj_(dim, table).
disj_(dim, woman).
disj_(dirt, dog).
disj_(dirt, helmet).
disj_(dirt, hill).
disj_(dirt, jacket).
disj_(dirt, man).
disj_(dirt, motocross).
disj_(dirt, pants).
disj_(dirt, person).
disj_(dirt, rider).
disj_(dirt, uniform).
disj_(dish, woman).
disj_(dog, doll).
disj_(dog, field).
disj_(dog, frisbee).
disj_(dog, girl).
disj_(dog, grass).
disj_(dog, ground).
disj_(dog, jacket).
disj_(dog, leaf).
disj_(dog, leg).
disj_(dog, man).
disj_(dog, monkey).
disj_(dog, mouth).
disj_(dog, outdoors).
disj_(dog, path).
disj_(dog, person).
disj_(dog, plant).
disj_(dog, pond).
disj_(dog, river).
disj_(dog, road).
disj_(dog, sand).
disj_(dog, shade).
disj_(dog, sidewalk).
disj_(dog, snow).
disj_(dog, soaker).
disj_(dog, soccer).
disj_(dog, stick).
disj_(dog, street).
disj_(dog, super).
disj_(dog, tail).
disj_(dog, tennis).
disj_(dog, toy).
disj_(dog, track).
disj_(dog, tree).
disj_(dog, water).
disj_(dog, woman).
disj_(dog, yard).
disj_(dog, zoo).
disj_(door, man).
disj_(dress, woman).
disj_(driver, hand).
disj_(driver, race).
disj_(driver, sky).
disj_(drum, man).
disj_(ear, girl).
disj_(ear, hair).
disj_(ear, piercing).
disj_(ear, tattoo).
disj_(edge, fountain).
disj_(edge, girl).
disj_(edge, water).
disj_(edge, woman).
disj_(egg, man).
disj_(egg, person).
disj_(egg, woman).
disj_(equipment, girl).
disj_(equipment, sound).
disj_(exercise, man).
disj_(eye, eyelid).
disj_(eyelid, liner).
disj_(eyelid, pencil).
disj_(eyelid, woman).
disj_(eye, liner).
disj_(eye, pencil).
disj_(eye, woman).
disj_(face, girl).
disj_(face, makeup).
disj_(face, man).
disj_(face, shirt).
disj_(face, woman).
disj_(family, man).
disj_(father, umbrella).
disj_(field, football).
disj_(field, grass).
disj_(field, man).
disj_(field, person).
disj_(field, player).
disj_(field, soccer).
disj_(finger, table).
disj_(finger, woman).
disj_(fire, person).
disj_(fire, torch).
disj_(fishing, man).
disj_(fish, man).
disj_(fish, woman).
disj_(flag, man).
disj_(flag, sunset).
disj_(floor, guinea).
disj_(floor, man).
disj_(floor, piece).
disj_(floor, pig).
disj_(flute, girl).
disj_(flute, guitar).
disj_(flute, man).
disj_(flute, woman).
disj_(food, kitten).
disj_(food, man).
disj_(food, tray).
disj_(food, woman).
disj_(football, jersey).
disj_(football, player).
disj_(football, touchdown).
disj_(forest, person).
disj_(fountain, girl).
disj_(fountain, shirt).
disj_(fountain, woman).
disj_(front, man).
disj_(front, person).
disj_(front, 't-shirt').
disj_(front, woman).
disj_(game, man).
disj_(garage, man).
disj_(garlic, woman).
disj_(gear, person).
disj_(girl, guitar).
disj_(girl, gym).
disj_(girl, hair).
disj_(girl, hand).
disj_(girl, leg).
disj_(girl, man).
disj_(girl, park).
disj_(girl, piercing).
disj_(girl, rope).
disj_(girl, shirt).
disj_(girl, sidewalk).
disj_(girl, stage).
disj_(girl, street).
disj_(girl, swing).
disj_(girl, tattoo).
disj_(girl, toy).
disj_(girl, uniform).
disj_(girl, water).
disj_(glass, man).
disj_(glass, woman).
disj_(glove, kick).
disj_(glove, man).
disj_(glove, practitioner).
disj_(glove, trainer).
disj_(goal, player).
disj_(goal, soccer).
disj_(grass, grey).
disj_(grass, man).
disj_(grass, mouth).
disj_(grass, person).
disj_(grass, soccer).
disj_(grass, tennis).
disj_(grass, water).
disj_(group, house).
disj_(group, jeans).
disj_(group, lady).
disj_(group, man).
disj_(group, room).
disj_(group, school).
disj_(group, stone).
disj_(group, street).
disj_(group, table).
disj_(group, uniform).
disj_(guinea, piece).
disj_(guitar, kid).
disj_(guitar, man).
disj_(guitar, person).
disj_(guitar, piano).
disj_(guitar, woman).
disj_(gun, man).
disj_(gun, water).
disj_(gym, jersey).
disj_(gym, man).
disj_(hair, man).
disj_(hair, piercing).
disj_(hair, tattoo).
disj_(hair, woman).
disj_(hand, hat).
disj_(hand, man).
disj_(hand, race).
disj_(hand, shirt).
disj_(hand, sky).
disj_(hand, sunglass).
disj_(hand, table).
disj_(hand, woman).
disj_(harp, man).
disj_(hat, kid).
disj_(hat, man).
disj_(hat, person).
disj_(hat, woman).
disj_(helmet, jacket).
disj_(helmet, motocross).
disj_(helmet, pants).
disj_(helmet, person).
disj_(helmet, rider).
disj_(hill, man).
disj_(hill, snow).
disj_(horse, man).
disj_(horse, person).
disj_(horse, road).
disj_(horse, track).
disj_(horse, woman).
disj_(house, jeans).
disj_(house, lady).
disj_(house, school).
disj_(house, stone).
disj_(house, street).
disj_(ice, person).
disj_(ingredient, person).
disj_(ingredient, woman).
disj_(instrument, man).
disj_(instrument, woman).
disj_(jacket, man).
disj_(jacket, motocross).
disj_(jacket, pants).
disj_(jacket, person).
disj_(jacket, rider).
disj_(jacket, wall).
disj_(jacket, woman).
disj_(jeans, lady).
disj_(jeans, man).
disj_(jeans, school).
disj_(jeans, shirt).
disj_(jeans, stone).
disj_(jeans, street).
disj_(jeans, woman).
disj_(jeep, man).
disj_(jeep, street).
disj_(jersey, man).
disj_(jersey, player).
disj_(jersey, touchdown).
disj_(kangaroo, woman).
disj_(keyboard, man).
disj_(keyboard, person).
disj_(kid, man).
disj_(kid, ocean).
disj_(kid, pool).
disj_(kid, snow).
disj_(kid, swimming).
disj_(kid, tongue).
disj_(kid, water).
disj_(kitten, tray).
disj_(knife, man).
disj_(knife, mushroom).
disj_(knife, person).
disj_(knife, tree).
disj_(knife, woman).
disj_(lady, meat).
disj_(lady, school).
disj_(lady, stone).
disj_(lady, street).
disj_(lady, tomato).
disj_(lawn, man).
disj_(leather, man).
disj_(liner, woman).
disj_(log, man).
disj_(machine, man).
disj_(makeup, woman).
disj_(man, meat).
disj_(man, microphone).
disj_(man, money).
disj_(man, motocross).
disj_(man, motorbike).
disj_(man, motorcycle).
disj_(man, mountain).
disj_(man, mouse).
disj_(man, mouth).
disj_(man, note).
disj_(man, ocean).
disj_(man, oil).
disj_(man, onion).
disj_(man, orange).
disj_(man, outdoors).
disj_(man, pan).
disj_(man, pants).
disj_(man, paper).
disj_(man, park).
disj_(man, path).
disj_(man, pencil).
disj_(man, phone).
disj_(man, piano).
disj_(man, picture).
disj_(man, piece).
disj_(man, pizza).
disj_(man, plastic).
disj_(man, pool).
disj_(man, pot).
disj_(man, potato).
disj_(man, purple).
disj_(man, race).
disj_(man, ramp).
disj_(man, river).
disj_(man, road).
disj_(man, rock).
disj_(man, room).
disj_(man, rope).
disj_(man, shirt).
disj_(man, shorts).
disj_(man, sidewalk).
disj_(man, slice).
disj_(man, snake).
disj_(man, soaker).
disj_(man, soccer).
disj_(man, sport).
disj_(man, stage).
disj_(man, street).
disj_(man, suit).
disj_(man, suitcase).
disj_(man, sunglass).
disj_(man, sunset).
disj_(man, super).
disj_(man, sword).
disj_(man, table).
disj_(man, tattoo).
disj_(man, tennis).
disj_(man, tomato).
disj_(man, top).
disj_(man, toy).
disj_(man, track).
disj_(man, tree).
disj_(man, trick).
disj_(man, trumpet).
disj_(man, trunk).
disj_(man, 't-shirt').
disj_(man, uniform).
disj_(man, vegetable).
disj_(man, vehicle).
disj_(man, video).
disj_(man, violin).
disj_(man, wall).
disj_(man, water).
disj_(man, waterfall).
disj_(man, wheel).
disj_(man, wheelie).
disj_(man, wilderness).
disj_(man, woman).
disj_(man, wood).
disj_(meat, pan).
disj_(meat, person).
disj_(meat, woman).
disj_(money, sign).
disj_(monkey, person).
disj_(monkey, zoo).
disj_(motocross, pants).
disj_(motocross, person).
disj_(motocross, rider).
disj_(motorbike, person).
disj_(motorcycle, person).
disj_(mountain, person).
disj_(mountain, top).
disj_(mouse, snake).
disj_(mouth, soaker).
disj_(mouth, super).
disj_(mouth, tennis).
disj_(mouth, yard).
disj_(mud, puddle).
disj_(noodle, person).
disj_(noodle, water).
disj_(noodle, woman).
disj_(ocean, person).
disj_(octopus, woman).
disj_(oil, person).
disj_(oil, pot).
disj_(okra, person).
disj_(onion, person).
disj_(onion, woman).
disj_(other, player).
disj_(outdoors, person).
disj_(outdoors, step).
disj_(paddling, pool).
disj_(pan, person).
disj_(pan, pot).
disj_(pants, person).
disj_(pants, rider).
disj_(pants, scarf).
disj_(pants, woman).
disj_(pan, woman).
disj_(paper, person).
disj_(park, person).
disj_(park, woman).
disj_(pasta, woman).
disj_(path, wilderness).
disj_(pencil, tattoo).
disj_(pencil, woman).
disj_(person, piano).
disj_(person, piece).
disj_(person, pink).
disj_(person, pot).
disj_(person, potato).
disj_(person, race).
disj_(person, raft).
disj_(person, restaurant).
disj_(person, road).
disj_(person, rock).
disj_(person, room).
disj_(person, rope).
disj_(person, sand).
disj_(person, scarf).
disj_(person, shirt).
disj_(person, snow).
disj_(person, snowboard).
disj_(person, street).
disj_(person, sun).
disj_(person, table).
disj_(person, tomato).
disj_(person, top).
disj_(person, torch).
disj_(person, trick).
disj_(person, uniform).
disj_(person, vegetable).
disj_(person, vehicle).
disj_(person, wall).
disj_(person, water).
disj_(person, wheel).
disj_(person, wood).
disj_(piece, pig).
disj_(piece, woman).
disj_(piercing, tattoo).
disj_(pitcher, water).
disj_(plant, sand).
disj_(player, soccer).
disj_(player, touchdown).
disj_(pool, swimming).
disj_(pork, woman).
disj_(potato, tomato).
disj_(potato, woman).
disj_(pot, vegetable).
disj_(pot, water).
disj_(pot, woman).
disj_(race, sky).
disj_(race, track).
disj_(ramp, trick).
disj_(road, wilderness).
disj_(road, woman).
disj_(rock, rope).
disj_(rock, shorts).
disj_(rock, top).
disj_(rock, wall).
disj_(rock, woman).
disj_(room, table).
disj_(room, woman).
disj_(rope, sidewalk).
disj_(rope, street).
disj_(scarf, silver).
disj_(scarf, woman).
disj_(school, stone).
disj_(school, street).
disj_(shade, tree).
disj_(shirt, sunglass).
disj_(shirt, table).
disj_(shirt, woman).
disj_(shrimp, woman).
disj_(sidewalk, street).
disj_(sidewalk, woman).
disj_(silver, woman).
disj_(skateboarder, trick).
disj_(skillet, woman).
disj_(snow, snowboarder).
disj_(soaker, super).
disj_(sport, uniform).
disj_(stage, woman).
disj_(stone, street).
disj_(street, toy).
disj_(street, vehicle).
disj_(street, woman).
disj_(suitcase, trunk).
disj_(suit, swimming).
disj_(surfboard, surfer).
disj_(surfer, water).
disj_(surfer, wave).
disj_(swimming, water).
disj_(table, woman).
disj_(thing, woman).
disj_(tofu, woman).
disj_(tomato, woman).
disj_('t-shirt', water).
disj_(wall, woman).
disj_(wall, wood).
disj_(water, woman).
disj_(whisk, woman).
disj_(wire, woman).
disj_(woman, wood).



