induced_knowledge('2_short', [
    disj(brown,large),
    disj(circle,dancing),
    disj('clean bike','yellow bike'),
    disj(cow,'eating hay'),
    disj('dirt bike','yellow bike'),
    disj(dog,'white animal'),
    disj(fighting,person),
    disj(grass,lawn),
    disj(jump,stand),
    disj(laughing,table),
    disj(lie,play),
    disj(man,woman),
    disj(motorbike,motorcyclist),
    disj(person,vehicle),
    disj(play,'put away'),
    disj(potato,woman),
    disj('put away','set up'),
    disj(race,runner),
    disj(run,walk),
    disj(sit,wade),
    isa_wn(a,four),
    isa_wn(a,two),
    isa_wn(a_few,several),
    isa_wn(acrobatics,trick),
    isa_wn(aim,draw),
    isa_wn(aim,handle),
    isa_wn(airplane,'animated airplane'),
    isa_wn(animal,dog),
    isa_wn(area,'snowy area'),
    isa_wn(area,'wooded area'),
    isa_wn('baby panda',cub),
    isa_wn(backyard,'back yard'),
    isa_wn(beach,sand),
    isa_wn(beach,'sandy shore'),
    isa_wn(beach,shore),
    isa_wn(black,little),
    isa_wn(blue,colored),
    isa_wn(boil,stir),
    isa_wn(bowl,cereal),
    isa_wn(boy,guy),
    isa_wn(boy,swimmer),
    isa_wn(brown,colored),
    isa_wn('brown hair',sunglass),
    isa_wn(brush,style),
    isa_wn(butter,'mixer butter'),
    isa_wn(camera,photo),
    isa_wn(camera,webcam),
    isa_wn(cap,hat),
    isa_wn(car,'burning car'),
    isa_wn(car,'racing vehicle'),
    isa_wn(carry,bite),
    isa_wn(cat,kitten),
    isa_wn('cattle pen',cattle),
    isa_wn(chair,'reading book'),
    isa_wn(chase,catch),
    isa_wn(child,'blond child'),
    isa_wn(child,'young child'),
    isa_wn(clean,erase),
    isa_wn('climb down',climb),
    isa_wn(clown,'costumed performer'),
    isa_wn(compete,race),
    isa_wn(container,box),
    isa_wn(container,'plastic container'),
    isa_wn(cook,roast),
    isa_wn(cover,snowy),
    isa_wn('cover hill',snow),
    isa_wn(cow,'eating hay'),
    isa_wn('cow pasture',cow),
    isa_wn(crowd,person),
    isa_wn(cut,chop),
    isa_wn(cut,'chop up'),
    isa_wn(cut,dice),
    isa_wn(device,telephone),
    isa_wn(dice,slice),
    isa_wn(dog,'bull dog'),
    isa_wn(dog,'white dog'),
    isa_wn(dress,veil),
    isa_wn(eat,bite),
    isa_wn('elderly woman','old person'),
    isa_wn(end,pencil),
    isa_wn('fall harmlessly',fall),
    isa_wn(female,girl),
    isa_wn(fit,fix),
    isa_wn(fix,apply),
    isa_wn(flip,jump),
    isa_wn(fountain,'ground fountain'),
    isa_wn(green,big),
    isa_wn(group,pack),
    isa_wn(guy,bloke),
    isa_wn('hang out',run),
    isa_wn(hat,'cowboy hat'),
    isa_wn(have,color),
    isa_wn(have,eat),
    isa_wn(heal,revive),
    isa_wn(hedgehog,'small animal'),
    isa_wn(hit,kick),
    isa_wn(hit,knock),
    isa_wn(hold,'pick up'),
    isa_wn(in,at),
    isa_wn(in,with),
    isa_wn(in_front_of,near),
    isa_wn(kangaroo,'baby kangaroo'),
    isa_wn(kid,boy),
    isa_wn(kitten,cat),
    isa_wn(lady,'topless girl'),
    isa_wn(left,side),
    isa_wn(look,'look around'),
    isa_wn(make,speak),
    isa_wn(man,biker),
    isa_wn(man,couple),
    isa_wn(man,'eating cereal'),
    isa_wn(man,'guitar player'),
    isa_wn(man,hiker),
    isa_wn(man,model),
    isa_wn(man,musician),
    isa_wn(man,player),
    isa_wn(man,racer),
    isa_wn(man,woman),
    isa_wn(market,store),
    isa_wn(mix,stir),
    isa_wn(monkey,chimp),
    isa_wn(motorcycle,motorbike),
    isa_wn('old woman','man'),
    isa_wn(on,in),
    isa_wn(open,bite),
    isa_wn(outside,around),
    isa_wn(pan,skillet),
    isa_wn(panda,'eating bamboo'),
    isa_wn('park porch',skateboard),
    isa_wn(parrot,'speaking parrot'),
    isa_wn(person,biker),
    isa_wn(person,cyclist),
    isa_wn(person,'football player'),
    isa_wn(person,'large person'),
    isa_wn(person,'one typing'),
    isa_wn(phone,toy),
    isa_wn('plastic sword','toy weapon'),
    isa_wn(play,sing),
    isa_wn(play,slide),
    isa_wn(play,swing),
    isa_wn(pot,bowl),
    isa_wn(puppy,'puppy rolling'),
    isa_wn(purple,colored),
    isa_wn(put,sprinkle),
    isa_wn(rabbit,bunny),
    isa_wn(rabbit,'stuffed bunny'),
    isa_wn(ride,race),
    isa_wn(river,'rocky stream'),
    isa_wn('roof top',roof),
    isa_wn(s,two),
    isa_wn(say,talk),
    isa_wn(scratch,stroke),
    isa_wn('sea shore',beach),
    isa_wn(ship,boat),
    isa_wn(shop,building),
    isa_wn(side,mountain),
    isa_wn(slide,crawl),
    isa_wn(spray,water),
    isa_wn(stand,wade),
    isa_wn(star,sky),
    isa_wn(statue,'gold statue'),
    isa_wn(stick,swing),
    isa_wn(stir,beat),
    isa_wn(strum,play),
    isa_wn(stunt,trick),
    isa_wn(sugar,spice),
    isa_wn(sunglass,'dark glass'),
    isa_wn('table tennis','ping pong'),
    isa_wn(take,relax),
    isa_wn(tan,brown),
    isa_wn(through,in),
    isa_wn(through,on),
    isa_wn(trek,hike),
    isa_wn(turn_around,go_around),
    isa_wn(up,down),
    isa_wn(vehicle,car),
    isa_wn(wakeboard,waterskie),
    isa_wn(wall,'brick wall'),
    isa_wn(watch,attend),
    isa_wn(white,large),
    isa_wn(wipe,spread),
    isa_wn(with,in),
    isa_wn(woman,cook),
    isa_wn(woman,'elegant woman'),
    isa_wn(woman,girl),
    isa_wn(yard,backyard),
    disj(ingredient,vegetable),
    disj(microphone,singing),
    disj('snowy path','snowy trail'),
    isa_wn(a,s),
    isa_wn(boy,'young boy'),
    isa_wn(chubby,boy),
    isa_wn(cord,rope),
    isa_wn(cut,'chop down'),
    isa_wn(escort,lead),
    isa_wn(guitar,singing),
    isa_wn(in,into),
    isa_wn(in,on),
    isa_wn(person,man),
    isa_wn(s,the),
    isa_wn(seashore,beach),
    isa_wn(the,one),
    isa_wn(the,s),
    isa_wn(woman,man),
    isa_wn(man,guy),
    isa_wn(piano,keyboard),
    isa_wn(sprinkle,put),
    isa_wn(in,through),
    isa_wn(cut,slice),
    %2nd loop
	isa_wn(at,on),
	isa_wn(bike,'dirt bike'),
	isa_wn('blue sky',air),
	isa_wn('brown field','broken volleyball'),
	isa_wn('eye liner',cosmetic),
	isa_wn(eyebrow,midspeech),
	isa_wn(field,lawn),
	isa_wn(game,'video game'),
	isa_wn(grass,field),
	isa_wn(photo,'hold drink'),
	isa_wn(potato,woman),
	isa_wn(snow,'white snow'),
	isa_wn(woman,potato),
	isa_wn(onto,on)
]).

induced_knowledge('2_short_cleaned', [
    %disj(brown,large),
    %disj(circle,dancing),
    %disj('clean bike','yellow bike'),
    %disj(cow,'eating hay'), %inconsustent with isa_wn(cow,'eating hay')
    %disj('dirt bike','yellow bike'),
    %disj(dog,'white animal'),
    %disj(fighting,person),
    %disj(grass,lawn),
    disj(jump,stand),
    disj(laughing,table),
    disj(lie,play), %?
    disj(man,woman),
    disj(motorbike,motorcyclist),
    disj(person,vehicle),
    disj(play,'put away'),
    disj(potato,woman),
    disj('put away','set up'),
    disj(race,runner),
    disj(run,walk),
    disj(sit,wade),
    %isa_wn(a,four),
    %isa_wn(a,two),
    isa_wn(a_few,several),
    isa_wn(acrobatics,trick),
    isa_wn(aim,draw), %?
    isa_wn(aim,handle), %?
    %isa_wn(airplane,'animated airplane'),
    %isa_wn(animal,dog),
    %isa_wn(area,'snowy area'),
    %isa_wn(area,'wooded area'),
    isa_wn('baby panda',cub),
    isa_wn(backyard,'back yard'),
    isa_wn(beach,sand),
    %isa_wn(beach,'sandy shore'), %?
    isa_wn(beach,shore),
    %isa_wn(black,little),
    isa_wn(blue,colored),
    %isa_wn(boil,stir),
    %isa_wn(bowl,cereal),
    isa_wn(boy,guy),
    %isa_wn(boy,swimmer),
    isa_wn(brown,colored),
    %isa_wn('brown hair',sunglass),
    isa_wn(brush,style), %?
    %isa_wn(butter,'mixer butter'),
    %isa_wn(camera,photo), %?
    %isa_wn(camera,webcam), %?
    isa_wn(cap,hat),
    %isa_wn(car,'burning car'),
    %isa_wn(car,'racing vehicle'),
    %isa_wn(carry,bite),
    %isa_wn(cat,kitten),
    isa_wn('cattle pen',cattle),
    %isa_wn(chair,'reading book'),
    %isa_wn(chase,catch),
    %isa_wn(child,'blond child'),
    isa_wn(child,'young child'),
    isa_wn(clean,erase),
    isa_wn('climb down',climb),
    isa_wn(clown,'costumed performer'),
    isa_wn(compete,race),
    %isa_wn(container,box),
    %isa_wn(container,'plastic container'),
    isa_wn(cook,roast),
    %isa_wn(cover,snowy),
    %isa_wn('cover hill',snow),
    %isa_wn(cow,'eating hay'),
    %isa_wn('cow pasture',cow),
    isa_wn(crowd,person),
    %isa_wn(cut,chop), %?
    %isa_wn(cut,'chop up'), %?
    %isa_wn(cut,dice), %?
    %isa_wn(device,telephone),
    %isa_wn(dice,slice), %?
    %isa_wn(dog,'bull dog'),
    %isa_wn(dog,'white dog'),
    %isa_wn(dress,veil),
    isa_wn(eat,bite),
    isa_wn('elderly woman','old person'),
    %isa_wn(end,pencil),
    isa_wn('fall harmlessly',fall),
    %isa_wn(female,girl),
    isa_wn(fit,fix),
    %isa_wn(fix,apply),
    %isa_wn(flip,jump),
    %isa_wn(fountain,'ground fountain'),
    %isa_wn(green,big),
    isa_wn(group,pack),
    isa_wn(guy,bloke),
    %isa_wn('hang out',run),
    %isa_wn(hat,'cowboy hat'),
    %isa_wn(have,color),
    %isa_wn(have,eat),
    isa_wn(heal,revive),
    isa_wn(hedgehog,'small animal'),
    isa_wn(hit,kick),
    isa_wn(hit,knock),
    %isa_wn(hold,'pick up'),
    isa_wn(in,at),
    isa_wn(in,with),
    isa_wn(in_front_of,near),
    %isa_wn(kangaroo,'baby kangaroo'),
    %isa_wn(kid,boy),
    isa_wn(kitten,cat),
    %isa_wn(lady,'topless girl'),
    isa_wn(left,side),
    %isa_wn(look,'look around'),
    %isa_wn(make,speak),
    %isa_wn(man,biker),
    %isa_wn(man,couple),
    %isa_wn(man,'eating cereal'),
    %isa_wn(man,'guitar player'),
    %isa_wn(man,hiker),
    %isa_wn(man,model),
    %isa_wn(man,musician),
    %isa_wn(man,player),
    %isa_wn(man,racer),
    %isa_wn(man,woman),
    isa_wn(market,store),
    isa_wn(mix,stir),
    %isa_wn(monkey,chimp), %?
    isa_wn(motorcycle,motorbike),
    %isa_wn('old woman',man),
    %isa_wn(on,in),
    %isa_wn(open,bite),
    isa_wn(outside,around),
    isa_wn(pan,skillet),
    %isa_wn(panda,'eating bamboo'),
    %isa_wn('park porch',skateboard),
    %isa_wn(parrot,'speaking parrot'),
    %isa_wn(person,biker),
    %isa_wn(person,cyclist),
    %isa_wn(person,'football player'),
    %isa_wn(person,'large person'),
    %isa_wn(person,'one typing'),
    %isa_wn(phone,toy),
    isa_wn('plastic sword','toy weapon'),
    %isa_wn(play,sing),
    %isa_wn(play,slide),
    %isa_wn(play,swing),
    isa_wn(pot,bowl),
    %isa_wn(puppy,'puppy rolling'),
    isa_wn(purple,colored),
    %isa_wn(put,sprinkle),
    isa_wn(rabbit,bunny),
    %isa_wn(rabbit,'stuffed bunny'),
    isa_wn(ride,race),
    %isa_wn(river,'rocky stream'),
    %isa_wn('roof top',roof),
    %isa_wn(s,two),
    isa_wn(say,talk),
    %isa_wn(scratch,stroke),
    isa_wn('sea shore',beach),
    isa_wn(ship,boat),
    isa_wn(shop,building),
    %isa_wn(side,mountain),
    isa_wn(slide,crawl),
    isa_wn(spray,water),
    %isa_wn(stand,wade),
    %isa_wn(star,sky),
    %isa_wn(statue,'gold statue'),
    %isa_wn(stick,swing),
    %isa_wn(stir,beat),
    isa_wn(strum,play),
    isa_wn(stunt,trick),
    isa_wn(sugar,spice),
    isa_wn(sunglass,'dark glass'),
    isa_wn('table tennis','ping pong'),
    %isa_wn(take,relax),
    isa_wn(tan,brown),
    isa_wn(through,in),
    isa_wn(through,on),
    isa_wn(trek,hike),
    isa_wn(turn_around,go_around),
    %isa_wn(up,down),
    %isa_wn(vehicle,car),
    %isa_wn(wakeboard,waterskie),
    %isa_wn(wall,'brick wall'),
    isa_wn(watch,attend),
    %isa_wn(white,large),
    isa_wn(wipe,spread),
    isa_wn(with,in),
    %isa_wn(woman,cook),
    %isa_wn(woman,'elegant woman'),
    %isa_wn(woman,girl),
    %isa_wn(yard,backyard), %!
    %disj(ingredient,vegetable),
    %disj(microphone,singing),
    disj('snowy path','snowy trail'),
    %isa_wn(a,s),
    %isa_wn(boy,'young boy'),
    %isa_wn(chubby,boy),
    isa_wn(cord,rope),
    isa_wn(cut,'chop down'),
    isa_wn(escort,lead),
    %isa_wn(guitar,singing),
    isa_wn(in,into),
    %isa_wn(in,on),
    %isa_wn(person,man),
    isa_wn(s,the),
    isa_wn(seashore,beach),
    isa_wn(the,one),
    %isa_wn(the,s),
    %isa_wn(woman,man),
    isa_wn(man,guy),
    isa_wn(piano,keyboard),
    isa_wn(sprinkle,put),
    isa_wn(in,through),
    isa_wn(cut,slice),
    %2nd loop
	isa_wn(at,on),
	isa_wn(bike,'dirt bike'),
	%isa_wn(blue sky,air),
	%isa_wn(brown field,broken volleyball),
	isa_wn('eye liner',cosmetic),
	%isa_wn(eyebrow,midspeech),
	%isa_wn(field,lawn),
	%isa_wn(game,video game),
	%isa_wn(grass,field),
	%isa_wn(photo,hold drink),
	%isa_wn(potato,woman),
	isa_wn(snow,'white snow'),
	%isa_wn(woman,potato),
	isa_wn(onto,on)
]).


induced_knowledge('2_short_fixed', [
    %disj(brown,large),
    %disj(circle,dancing),
    %disj('clean bike','yellow bike'),
    %disj(cow,'eating hay'), %inconsustent with isa_wn(cow,'eating hay')
    %disj('dirt bike','yellow bike'),
    %disj(dog,'white animal'),
    %disj(fighting,person),
    isa_wn(grass,lawn), %disj(grass,lawn),
    disj(jump,stand),
    disj(laughing,table),
    disj(lie,play),
    disj(man,woman),
    disj(motorbike,motorcyclist),
    disj(person,vehicle),
    disj(play,'put away'),
    disj(potato,woman),
    disj('put away','set up'),
    disj(race,runner),
    disj(run,walk),
    disj(sit,wade),
    isa_wn(four,a), %isa_wn(a,four),
    isa_wn(two,a), %isa_wn(a,two),
    isa_wn(a_few,several),
    isa_wn(acrobatics,trick),
    isa_wn(aim,draw), %?
    isa_wn(aim,handle), %?
    %isa_wn(airplane,'animated airplane'),
    %isa_wn(animal,dog),
    %isa_wn(area,'snowy area'),
    %isa_wn(area,'wooded area'),
    isa_wn('baby panda',cub),
    isa_wn(backyard,'back yard'),
    isa_wn(beach,sand),
    %isa_wn(beach,'sandy shore'), %?
    isa_wn(beach,shore),
    %isa_wn(black,little),
    isa_wn(blue,colored),
    disj(boil,stir),%isa_wn(boil,stir),
    disj(bowl,cereal),%isa_wn(bowl,cereal),
    isa_wn(boy,guy),
    %isa_wn(boy,swimmer),
    isa_wn(brown,colored),
    disj('brown hair',sunglass),%isa_wn('brown hair',sunglass),
    isa_wn(brush,style), %?
    %isa_wn(butter,'mixer butter'),
    disj(camera,photo),%isa_wn(camera,photo), %?
    isa_wn(webcam,camera),%isa_wn(camera,webcam), %?
    isa_wn(cap,hat),
    %isa_wn(car,'burning car'),
    isa_wn('racing vehicle',car),%isa_wn(car,'racing vehicle'),
    %isa_wn(carry,bite),
    %isa_wn(cat,kitten),
    isa_wn('cattle pen',cattle),
    disj(chair,'reading book'),%isa_wn(chair,'reading book'),
    %isa_wn(chase,catch),
    %isa_wn(child,'blond child'),
    isa_wn(child,'young child'),
    isa_wn(clean,erase),
    isa_wn('climb down',climb),
    isa_wn(clown,'costumed performer'),
    isa_wn(compete,race),
    isa_wn(box,container),%isa_wn(container,box),
    %isa_wn(container,'plastic container'),
    isa_wn(cook,roast),
    %isa_wn(cover,snowy),
    isa_wn(snowy,cover),
    %isa_wn('cover hill',snow),
    %isa_wn(cow,'eating hay'),
    %isa_wn('cow pasture',cow),
    %isa_wn(crowd,person),
    isa_wn(chop,cut),%isa_wn(cut,chop), %?
    isa_wn('chop up',cut),%isa_wn(cut,'chop up'), %?
    isa_wn(dice,cut), %isa_wn(cut,dice), %?
    isa_wn(telephone,device),%isa_wn(device,telephone),
    %isa_wn(dice,slice), %?
    %isa_wn(dog,'bull dog'),
    %isa_wn(dog,'white dog'),
    %isa_wn(dress,veil),
    isa_wn(eat,bite),
    isa_wn('elderly woman','old person'),
    disj(end,pencil),%isa_wn(end,pencil),
    isa_wn('fall harmlessly',fall),
    %isa_wn(female,girl),
    isa_wn(fit,fix),
    %isa_wn(fix,apply),
    %isa_wn(flip,jump),
    %isa_wn(fountain,'ground fountain'),
    %isa_wn(green,big),
    isa_wn(group,pack),
    isa_wn(guy,bloke),
    %isa_wn('hang out',run),
    %isa_wn(hat,'cowboy hat'),
    %isa_wn(have,color),
    %isa_wn(have,eat),
    isa_wn(heal,revive),
    isa_wn(hedgehog,'small animal'),
    isa_wn(hit,kick),
    isa_wn(hit,knock),
    %isa_wn(hold,'pick up'),
    isa_wn(in,at),
    isa_wn(in,with),
    isa_wn(in_front_of,near),
    %isa_wn(kangaroo,'baby kangaroo'),
    %isa_wn(kid,boy),
    isa_wn(kitten,cat),
    %isa_wn(lady,'topless girl'),
    isa_wn(left,side),
    %isa_wn(look,'look around'),
    %isa_wn(make,speak),
    %isa_wn(man,biker),
    %isa_wn(man,couple),
    %isa_wn(man,'eating cereal'),
    %isa_wn(man,'guitar player'),
    %isa_wn(man,hiker),
    %isa_wn(man,model),
    %isa_wn(man,musician),
    %isa_wn(man,player),
    %isa_wn(man,racer),
    %isa_wn(man,woman),
    isa_wn(market,store),
    isa_wn(mix,stir),
    %isa_wn(monkey,chimp), %?
    isa_wn(motorcycle,motorbike),
    %isa_wn('old woman',man),
    %isa_wn(on,in),
    %isa_wn(open,bite),
    isa_wn(outside,around),
    isa_wn(pan,skillet),
    %isa_wn(panda,'eating bamboo'),
    %isa_wn('park porch',skateboard),
    %isa_wn(parrot,'speaking parrot'),
    %isa_wn(person,biker),
    %isa_wn(person,cyclist),
    %isa_wn(person,'football player'),
    %isa_wn(person,'large person'),
    %isa_wn(person,'one typing'),
    %isa_wn(phone,toy),
    isa_wn('plastic sword','toy weapon'),
    %isa_wn(play,sing),
    %isa_wn(play,slide),
    %isa_wn(play,swing),
    isa_wn(pot,bowl),
    %isa_wn(puppy,'puppy rolling'),
    isa_wn(purple,colored),
    %isa_wn(put,sprinkle),
    isa_wn(rabbit,bunny),
    %isa_wn(rabbit,'stuffed bunny'),
    isa_wn(ride,race),
    %isa_wn(river,'rocky stream'),
    %isa_wn('roof top',roof),
    %isa_wn(s,two),
    isa_wn(say,talk),
    %isa_wn(scratch,stroke),
    isa_wn('sea shore',beach),
    isa_wn(ship,boat),
    isa_wn(shop,building),
    %isa_wn(side,mountain),
    isa_wn(slide,crawl),
    isa_wn(spray,water),
    %isa_wn(stand,wade),
    %isa_wn(star,sky),
    %isa_wn(statue,'gold statue'),
    %isa_wn(stick,swing),
    %isa_wn(stir,beat),
    isa_wn(strum,play),
    isa_wn(stunt,trick),
    isa_wn(sugar,spice),
    isa_wn(sunglass,'dark glass'),
    isa_wn('table tennis','ping pong'),
    %isa_wn(take,relax),
    isa_wn(tan,brown),
    isa_wn(through,in),
    isa_wn(through,on),
    isa_wn(trek,hike),
    isa_wn(turn_around,go_around),
    %isa_wn(up,down),
    %isa_wn(vehicle,car),
    %isa_wn(wakeboard,waterskie),
    %isa_wn(wall,'brick wall'),
    isa_wn(watch,attend),
    %isa_wn(white,large),
    isa_wn(wipe,spread),
    isa_wn(with,in),
    %isa_wn(woman,cook),
    %isa_wn(woman,'elegant woman'),
    %isa_wn(woman,girl),
    isa_wn(backyard,yard),%isa_wn(yard,backyard), %!
    %disj(ingredient,vegetable),
    %disj(microphone,singing),
    disj('snowy path','snowy trail'),
    %isa_wn(a,s),
    %isa_wn(boy,'young boy'),
    %isa_wn(chubby,boy),
    isa_wn(cord,rope),
    isa_wn(cut,'chop down'),
    isa_wn(escort,lead),
    %isa_wn(guitar,singing),
    isa_wn(in,into),
    %isa_wn(in,on),
    %isa_wn(person,man),
    isa_wn(s,the),
    isa_wn(seashore,beach),
    isa_wn(the,one),
    %isa_wn(the,s),
    disj(woman,man),%isa_wn(woman,man),
    isa_wn(man,guy),
    isa_wn(piano,keyboard),
    isa_wn(sprinkle,put),
    isa_wn(in,through),
    isa_wn(cut,slice),
    %2nd loop
	isa_wn(at,on),
	isa_wn(bike,'dirt bike'),
	%isa_wn(blue sky,air),
	disj('brown field','broken volleyball'),%isa_wn(brown field,broken volleyball),
	isa_wn('eye liner',cosmetic),
	disj(eyebrow,midspeech), %isa_wn(eyebrow,midspeech),
	%isa_wn(field,lawn),
	%isa_wn(game,video game),
	%isa_wn(grass,field),
	disj(photo,'hold drink'), %isa_wn(photo,'hold drink'),
	disj(potato,woman),%isa_wn(potato,woman),
	isa_wn(snow,'white snow'),
	disj(woman,potato),%isa_wn(woman,potato),
	isa_wn(onto,on)    
]).
