:- op(601, xfx, (/)).
:- op(601, xfx, (\)).
:- multifile ccg/2, id/2.
:- discontiguous ccg/2, id/2.

ccg(1,
 ba(s:dcl,
  fa(np:nb,
   t(np:nb/n, 'All', 'all', 'DT', 'I-NP', 'O'),
   t(n, 'men', 'man', 'NNS', 'I-NP', 'O')),
  fa(s:dcl\np,
   t((s:dcl\np)/(s:adj\np), 'are', 'be', 'VBP', 'I-VP', 'O'),
   t(s:adj\np, 'mortal', 'mortal', 'JJ', 'I-ADJP', 'O')))).

ccg(2,
 ba(s:dcl,
  lx(np, n,
   t(n, 'Socrates', 'Socrates', 'NNP', 'I-NP', 'I-ORG')),
  fa(s:dcl\np,
   t((s:dcl\np)/np, 'is', 'be', 'VBZ', 'I-VP', 'O'),
   fa(np:nb,
    t(np:nb/n, 'a', 'a', 'DT', 'I-NP', 'O'),
    t(n, 'man', 'man', 'NN', 'I-NP', 'O'))))).

ccg(3,
 ba(s:dcl,
  lx(np, n,
   t(n, 'Socrates', 'Socrates', 'NNP', 'I-NP', 'I-ORG')),
  fa(s:dcl\np,
   t((s:dcl\np)/np, 'is', 'be', 'VBZ', 'I-VP', 'O'),
   fa(np:nb,
    t(np:nb/n, 'a', 'a', 'DT', 'I-NP', 'O'),
    t(n, 'mortal', 'mortal', 'JJ', 'I-NP', 'O'))))).


ccg(28,
 ba(s:dcl,
  lx(np, n,
   ba(n,
    t(n, 'John', 'John', 'NNP', 'I-NP', 'I-PER'),
    conj(n\n, n,
     t(conj, 'and', 'and', 'CC', 'I-NP', 'I-PER'),
     t(n, 'Mary', 'Mary', 'NNP', 'I-NP', 'I-PER')))),
  fa(s:dcl\np,
   t((s:dcl\np)/(s:ng\np), 'are', 'be', 'VBP', 'I-VP', 'O'),
   fa(s:ng\np,
    t((s:ng\np)/np, 'watching', 'watch', 'VBG', 'I-VP', 'O'),
    lx(np, n,
     ba(n,
      t(n, 'somebody', 'somebody', 'DT', 'I-NP', 'O'),
      lx(n\n, s:ng\np,
       ba(s:ng\np,
        t(s:ng\np, 'falling', 'fall', 'VBG', 'I-VP', 'O'),
        fa((s:ng\np)\(s:ng\np),
         t(((s:ng\np)\(s:ng\np))/np, 'on', 'on', 'IN', 'I-PP', 'O'),
         lx(np, n,
          t(n, 'ice', 'ice', 'NN', 'I-NP', 'O'))))))))))).

ccg(61,
 ba(s:dcl,
  fa(np,
   t(np/n, 'Every', 'every', 'DT', 'I-NP', 'O'),
   ba(n,
    ba(n,
     t(n, 'shirt', 'shirt', 'NN', 'I-NP', 'O'),
     fa(n\n,
      t((n\n)/np, 'in', 'in', 'IN', 'I-PP', 'O'),
      lx(np, n,
       t(n, 'Zara', 'Zara', 'NNP', 'I-NP', 'I-LOC')))),
    lx(n\n, s:dcl/np,
     fc(s:dcl/np,
      tr(s:dcl/(s:dcl\np),
       t(np, 'I', 'I', 'PRP', 'B-NP', 'O')),
      t((s:dcl\np)/np, 'liked', 'like', 'VBD', 'I-VP', 'O'))))),
  fa(s:dcl\np,
   t((s:dcl\np)/(s:pss\np), 'are', 'be', 'VBP', 'B-VP', 'O'),
   fa(s:pss\np,
    t((s:pss\np)/pr, 'sold', 'sell', 'VBN', 'I-VP', 'O'),
    t(pr, 'out', 'out', 'RP', 'I-PRT', 'O'))))).


ccg(62,
 ba(s:dcl,
  ba(np,
   ba(np,
    fa(np:nb,
     t(np:nb/n, 'Every', 'every', 'DT', 'I-NP', 'O'),
     t(n, 'shirt', 'shirt', 'NN', 'I-NP', 'O')),
    fa(np\np,
     t((np\np)/np, 'in', 'in', 'IN', 'I-PP', 'O'),
     lx(np, n,
      t(n, 'Zara', 'Zara', 'NNP', 'I-NP', 'I-LOC')))),
   lx(np\np, s:dcl/np,
    fc(s:dcl/np,
     tr(s:dcl/(s:dcl\np),
      t(np, 'I', 'I', 'PRP', 'B-NP', 'O')),
     t((s:dcl\np)/np, 'liked', 'like', 'VBD', 'I-VP', 'O')))),
  fa(s:dcl\np,
   t((s:dcl\np)/(s:pss\np), 'are', 'be', 'VBP', 'B-VP', 'O'),
   ba(s:pss\np,
    t(s:pss\np, 'sold', 'sell', 'VBN', 'I-VP', 'O'),
    t((s:pss\np)\(s:pss\np), 'out', 'out', 'RP', 'I-PRT', 'O'))))).

ccg(33,
 ba(s:dcl,
  ba(np:nb,
   fa(np:nb,
    t(np:nb/n,'Every',every,'DT','O','O'),
    t(n,shirt,shirt,'NN','O','O')),
   fa(np\np,
    t((np\np)/np,in,in,'IN','O','O'),
    ba(np,
     lx(np, n,
      t(n,'Zara','Zara','NNP','O','I-LOC')),
     lx(np\np, s:dcl/np,
      fc(s:dcl/np,
       tr(s:_G2132/ (s:_G2138\np),
        t(np,'I',i,'PRP','O','O')),
       t((s:dcl\np)/np,liked,lik,'VBD','O','O')))))),
  fa(s:dcl\np,
   t((s:dcl\np)/ (s:pss\np),is,be,'VBZ','O','O'),
   ba(s:pss\np,
    t(s:pss\np,sold,sell,'VBN','O','O'),
    t((s\np)\ (s\np),out,out,'RP','O','O'))))).

ccg(34,
 ba(s:dcl,
  ba(np:nb,
   fa(np:nb,
    t(np:nb/n,'Every',every,'DT','O','O'),
    t(n,shirt,shirt,'NN','O','O')),
   fa(np\np,
    t((np\np)/np,in,in,'IN','O','O'),
    ba(np,
     lx(np, n,
      t(n,'Zara','Zara','NNP','O','I-LOC')),
     lx(np\np, s:dcl/np,
      fc(s:dcl/np,
       tr(s:_G1944/ (s:_G1950\np),
        t(np,'I',i,'PRP','O','O')),
       t((s:dcl\np)/np,liked,lik,'VBD','O','O')))))),
  ba(s:dcl\np,
   fa(s:dcl\np,
    t((s:dcl\np)/ (s:pss\np),is,be,'VBZ','O','O'),
    t(s:pss\np,sold,sell,'VBN','O','O')),
   t((s\np)\ (s\np),out,out,'RP','O','O')))).


ccg(35,
 ba(s:dcl,
  ba(np:nb,
   fa(np:nb,
    t(np:nb/n,'Every',every,'DT','O','O'),
    t(n,shirt,shirt,'NN','O','O')),
   fa(np\np,
    t((np\np)/np,in,in,'IN','O','O'),
    ba(np,
     lx(np, n,
      t(n,'Zara','Zara','NNP','O','I-LOC')),
     lx(np\np, s:dcl/np,
      fc(s:dcl/np,
       tr(s:_G2132/ (s:_G2138\np),
        t(np,'I',i,'PRP','O','O')),
       t((s:dcl\np)/np,liked,lik,'VBD','O','O')))))),
  ba(s:dcl\np,
   fa(s:dcl\np,
    t((s:dcl\np)/ (s:pss\np),is,be,'VBZ','O','O'),
    t(s:pss\np,sold,sell,'VBN','O','O')),
   t((s\np)\ (s\np),out,out,'RP','O','O')))).

ccg(36,
 ba(s:dcl,
  ba(np:nb,
   fa(np:nb,
    t(np:nb/n,'Every',every,'DT','O','O'),
    t(n,shirt,shirt,'NN','O','O')),
   fa(np\np,
    t((np\np)/np,in,in,'IN','O','O'),
    ba(np,
     lx(np, n,
      t(n,'Zara','Zara','NNP','O','I-LOC')),
     lx(np\np, s:dcl/np,
      fc(s:dcl/np,
       tr(s:_G1944/ (s:_G1950\np),
        t(np,'I',i,'PRP','O','O')),
       t((s:dcl\np)/np,liked,lik,'VBD','O','O')))))),
  fa(s:dcl\np,
   t((s:dcl\np)/ (s:pss\np),is,be,'VBZ','O','O'),
   ba(s:pss\np,
    t(s:pss\np,sold,sell,'VBN','O','O'),
    t((s\np)\ (s\np),out,out,'RP','O','O'))))).


ccg(101,
 ba(s:dcl,
  ba(np:nb,
   ba(np:nb,
    fa(np:nb,
     t(np:nb/n,'Every',every,'DT','O','O'),
     t(n,shirt,shirt,'NN','O','O')),
    fa(np\np,
     t((np\np)/np,in,in,'IN','O','O'),
     lx(np, n,
      t(n,'Zara','Zara','NNP','O','I-LOC')))),
   lx(np\np, s:dcl/np,
    fc(s:dcl/np,
     tr(s:_G2444/ (s:_G2450\np),
      t(np,'I',i,'PRP','O','O')),
     t((s:dcl\np)/np,liked,lik,'VBD','O','O')))),
  fa(s:dcl\np,
   t((s:dcl\np)/ (s:pss\np),is,be,'VBZ','O','O'),
   ba(s:pss\np,
    t(s:pss\np,sold,sell,'VBN','O','O'),
    t((s\np)\ (s\np),out,out,'RP','O','O'))))).

ccg(102,
 ba(s:dcl,
  ba(np:nb,
   ba(np:nb,
    fa(np:nb,
     t(np:nb/n,'Every',every,'DT','O','O'),
     t(n,shirt,shirt,'NN','O','O')),
    fa(np\np,
     t((np\np)/np,in,in,'IN','O','O'),
     lx(np, n,
      t(n,'Zara','Zara','NNP','O','I-LOC')))),
   lx(np\np, s:dcl/np,
    fc(s:dcl/np,
     tr(s:_G1881/ (s:_G1887\np),
      t(np,'I',i,'PRP','O','O')),
     t((s:dcl\np)/np,liked,lik,'VBD','O','O')))),
  ba(s:dcl\np,
   fa(s:dcl\np,
    t((s:dcl\np)/ (s:pss\np),is,be,'VBZ','O','O'),
    t(s:pss\np,sold,sell,'VBN','O','O')),
   t((s\np)\ (s\np),out,out,'RP','O','O')))).

ccg(103,
 ba(s:dcl,
  ba(np:nb,
   fa(np:nb,
    t(np:nb/n,'Every',every,'DT','O','O'),
    t(n,shirt,shirt,'NN','O','O')),
   fa(np\np,
    t((np\np)/np,in,in,'IN','O','O'),
    ba(np,
     lx(np, n,
      t(n,'Zara','Zara','NNP','O','I-LOC')),
     lx(np\np, s:dcl/np,
      fc(s:dcl/np,
       tr(s:_G1794/ (s:_G1800\np),
        t(np,'I',i,'PRP','O','O')),
       t((s:dcl\np)/np,liked,lik,'VBD','O','O')))))),
  fa(s:dcl\np,
   t((s:dcl\np)/ (s:pss\np),is,be,'VBZ','O','O'),
   ba(s:pss\np,
    t(s:pss\np,sold,sell,'VBN','O','O'),
    t((s\np)\ (s\np),out,out,'RP','O','O'))))).

ccg(104,
 ba(s:dcl,
  ba(np:nb,
   fa(np:nb,
    t(np:nb/n,'Every',every,'DT','O','O'),
    t(n,shirt,shirt,'NN','O','O')),
   fa(np\np,
    t((np\np)/np,in,in,'IN','O','O'),
    ba(np,
     lx(np, n,
      t(n,'Zara','Zara','NNP','O','I-LOC')),
     lx(np\np, s:dcl/np,
      fc(s:dcl/np,
       tr(s:_G1692/ (s:_G1698\np),
        t(np,'I',i,'PRP','O','O')),
       t((s:dcl\np)/np,liked,lik,'VBD','O','O')))))),
  ba(s:dcl\np,
   fa(s:dcl\np,
    t((s:dcl\np)/ (s:pss\np),is,be,'VBZ','O','O'),
    t(s:pss\np,sold,sell,'VBN','O','O')),
   t((s\np)\ (s\np),out,out,'RP','O','O')))).

ccg(105,
 ba(s:dcl,
  ba(np:nb,
   fa(np:nb,
    t(np:nb/n,'Every',every,'DT','O','O'),
    t(n,shirt,shirt,'NN','O','O')),
   lx(np\np, s:dcl/np,
    fc(s:dcl/np,
     fa(s/s,
      t((s/s)/np,in,in,'IN','O','O'),
      lx(np, n,
       t(n,'Zara','Zara','NNP','O','I-LOC'))),
     fc(s:dcl/np,
      tr(s:_G1590/ (s:_G1596\np),
       t(np,'I',i,'PRP','O','O')),
      t((s:dcl\np)/np,liked,lik,'VBD','O','O'))))),
  ba(s:dcl\np,
   fa(s:dcl\np,
    t((s:dcl\np)/ (s:pss\np),is,be,'VBZ','O','O'),
    t(s:pss\np,sold,sell,'VBN','O','O')),
   t((s\np)\ (s\np),out,out,'RP','O','O')))).

ccg(106,
 ba(s:dcl,
  ba(np:nb,
   fa(np:nb,
    t(np:nb/n,'Every',every,'DT','O','O'),
    t(n,shirt,shirt,'NN','O','O')),
   lx(np\np, s:dcl/np,
    fc(s:dcl/np,
     fa(s/s,
      t((s/s)/np,in,in,'IN','O','O'),
      lx(np, n,
       t(n,'Zara','Zara','NNP','O','I-LOC'))),
     fc(s:dcl/np,
      tr(s:_G1482/ (s:_G1488\np),
       t(np,'I',i,'PRP','O','O')),
      t((s:dcl\np)/np,liked,lik,'VBD','O','O'))))),
  fa(s:dcl\np,
   t((s:dcl\np)/ (s:pss\np),is,be,'VBZ','O','O'),
   ba(s:pss\np,
    t(s:pss\np,sold,sell,'VBN','O','O'),
    t((s\np)\ (s\np),out,out,'RP','O','O'))))).

ccg(107,
 ba(s:dcl,
  ba(np:nb,
   fa(np:nb,
    t(np:nb/n,'Every',every,'DT','O','O'),
    t(n,shirt,shirt,'NN','O','O')),
   fa(np\np,
    t((np\np)/np,in,in,'IN','O','O'),
    ba(np,
     lx(np, n,
      t(n,'Zara','Zara','NNP','O','I-LOC')),
     lx(np\np, s:dcl/np,
      fc(s:dcl/np,
       tr(s:_G1365/ (s:_G1371\np),
        lx(np, n,
         t(n,'I',i,'PRP','O','O'))),
       t((s:dcl\np)/np,liked,lik,'VBD','O','O')))))),
  ba(s:dcl\np,
   fa(s:dcl\np,
    t((s:dcl\np)/ (s:pss\np),is,be,'VBZ','O','O'),
    t(s:pss\np,sold,sell,'VBN','O','O')),
   t((s\np)\ (s\np),out,out,'RP','O','O')))).

ccg(108,
 ba(s:dcl,
  ba(np:nb,
   fa(np:nb,
    t(np:nb/n,'Every',every,'DT','O','O'),
    t(n,shirt,shirt,'NN','O','O')),
   fa(np\np,
    t((np\np)/np,in,in,'IN','O','O'),
    ba(np,
     lx(np, n,
      t(n,'Zara','Zara','NNP','O','I-LOC')),
     lx(np\np, s:dcl/np,
      fc(s:dcl/np,
       tr(s:_G1272/ (s:_G1278\np),
        lx(np, n,
         t(n,'I',i,'PRP','O','O'))),
       t((s:dcl\np)/np,liked,lik,'VBD','O','O')))))),
  fa(s:dcl\np,
   t((s:dcl\np)/ (s:pss\np),is,be,'VBZ','O','O'),
   ba(s:pss\np,
    t(s:pss\np,sold,sell,'VBN','O','O'),
    t((s\np)\ (s\np),out,out,'RP','O','O'))))).

ccg(109,
 ba(s:dcl,
  ba(np:nb,
   ba(np:nb,
    fa(np:nb,
     t(np:nb/n,'Every',every,'DT','O','O'),
     t(n,shirt,shirt,'NN','O','O')),
    fa(np\np,
     t((np\np)/np,in,in,'IN','O','O'),
     lx(np, n,
      t(n,'Zara','Zara','NNP','O','I-LOC')))),
   lx(np\np, s:dcl/np,
    fc(s:dcl/np,
     tr(s:_G1170/ (s:_G1176\np),
      lx(np, n,
       t(n,'I',i,'PRP','O','O'))),
     t((s:dcl\np)/np,liked,lik,'VBD','O','O')))),
  ba(s:dcl\np,
   fa(s:dcl\np,
    t((s:dcl\np)/ (s:pss\np),is,be,'VBZ','O','O'),
    t(s:pss\np,sold,sell,'VBN','O','O')),
   t((s\np)\ (s\np),out,out,'RP','O','O')))).

ccg(110,
 ba(s:dcl,
  ba(np:nb,
   ba(np:nb,
    fa(np:nb,
     t(np:nb/n,'Every',every,'DT','O','O'),
     t(n,shirt,shirt,'NN','O','O')),
    fa(np\np,
     t((np\np)/np,in,in,'IN','O','O'),
     lx(np, n,
      t(n,'Zara','Zara','NNP','O','I-LOC')))),
   lx(np\np, s:dcl/np,
    fc(s:dcl/np,
     tr(s:_G1065/ (s:_G1071\np),
      lx(np, n,
       t(n,'I',i,'PRP','O','O'))),
     t((s:dcl\np)/np,liked,lik,'VBD','O','O')))),
  fa(s:dcl\np,
   t((s:dcl\np)/ (s:pss\np),is,be,'VBZ','O','O'),
   ba(s:pss\np,
    t(s:pss\np,sold,sell,'VBN','O','O'),
    t((s\np)\ (s\np),out,out,'RP','O','O'))))).

ccg(111,
 ba(s:dcl,
  ba(np:nb,
   fa(np:nb,
    t(np:nb/n,'Every',every,'DT','O','O'),
    ba(n,
     t(n,shirt,shirt,'NN','O','O'),
     fa(n\n,
      t((n\n)/np,in,in,'IN','O','O'),
      lx(np, n,
       t(n,'Zara','Zara','NNP','O','I-LOC'))))),
   lx(np\np, s:dcl/np,
    fc(s:dcl/np,
     tr(s:_G960/ (s:_G966\np),
      t(np,'I',i,'PRP','O','O')),
     t((s:dcl\np)/np,liked,lik,'VBD','O','O')))),
  fa(s:dcl\np,
   t((s:dcl\np)/ (s:pss\np),is,be,'VBZ','O','O'),
   ba(s:pss\np,
    t(s:pss\np,sold,sell,'VBN','O','O'),
    t((s\np)\ (s\np),out,out,'RP','O','O'))))).

ccg(112,
 ba(s:dcl,
  ba(np:nb,
   fa(np:nb,
    t(np:nb/n,'Every',every,'DT','O','O'),
    ba(n,
     t(n,shirt,shirt,'NN','O','O'),
     fa(n\n,
      t((n\n)/np,in,in,'IN','O','O'),
      lx(np, n,
       t(n,'Zara','Zara','NNP','O','I-LOC'))))),
   lx(np\np, s:dcl/np,
    fc(s:dcl/np,
     tr(s:_G858/ (s:_G864\np),
      t(np,'I',i,'PRP','O','O')),
     t((s:dcl\np)/np,liked,lik,'VBD','O','O')))),
  ba(s:dcl\np,
   fa(s:dcl\np,
    t((s:dcl\np)/ (s:pss\np),is,be,'VBZ','O','O'),
    t(s:pss\np,sold,sell,'VBN','O','O')),
   t((s\np)\ (s\np),out,out,'RP','O','O')))).

ccg(113,
 ba(s:dcl,
  fa(np:nb,
   t(np:nb/n,'Every',every,'DT','O','O'),
   ba(n,
    t(n,shirt,shirt,'NN','O','O'),
    fa(n\n,
     t((n\n)/np,in,in,'IN','O','O'),
     ba(np,
      lx(np, n,
       t(n,'Zara','Zara','NNP','O','I-LOC')),
      lx(np\np, s:dcl/np,
       fc(s:dcl/np,
        tr(s:_G741/ (s:_G747\np),
         t(np,'I',i,'PRP','O','O')),
        t((s:dcl\np)/np,liked,lik,'VBD','O','O'))))))),
  fa(s:dcl\np,
   t((s:dcl\np)/ (s:pss\np),is,be,'VBZ','O','O'),
   ba(s:pss\np,
    t(s:pss\np,sold,sell,'VBN','O','O'),
    t((s\np)\ (s\np),out,out,'RP','O','O'))))).

ccg(114,
 ba(s:dcl,
  fa(np:nb,
   t(np:nb/n,'Every',every,'DT','O','O'),
   ba(n,
    t(n,shirt,shirt,'NN','O','O'),
    fa(n\n,
     t((n\n)/np,in,in,'IN','O','O'),
     ba(np,
      lx(np, n,
       t(n,'Zara','Zara','NNP','O','I-LOC')),
      lx(np\np, s:dcl/np,
       fc(s:dcl/np,
        tr(s:_G657/ (s:_G663\np),
         t(np,'I',i,'PRP','O','O')),
        t((s:dcl\np)/np,liked,lik,'VBD','O','O'))))))),
  ba(s:dcl\np,
   fa(s:dcl\np,
    t((s:dcl\np)/ (s:pss\np),is,be,'VBZ','O','O'),
    t(s:pss\np,sold,sell,'VBN','O','O')),
   t((s\np)\ (s\np),out,out,'RP','O','O')))).

ccg(115,
 ba(s:dcl,
  fa(np:nb,
   t(np:nb/n,'Every',every,'DT','O','O'),
   t(n,shirt,shirt,'NN','O','O')),
  fa(s:dcl\np,
   fa((s\np)/ (s\np),
    t(((s\np)/ (s\np))/np,in,in,'IN','O','O'),
    ba(np,
     lx(np, n,
      t(n,'Zara','Zara','NNP','O','I-LOC')),
     lx(np\np, s:dcl/np,
      fc(s:dcl/np,
       tr(s:_G558/ (s:_G564\np),
        t(np,'I',i,'PRP','O','O')),
       t((s:dcl\np)/np,liked,lik,'VBD','O','O'))))),
   fa(s:dcl\np,
    t((s:dcl\np)/ (s:pss\np),is,be,'VBZ','O','O'),
    ba(s:pss\np,
     t(s:pss\np,sold,sell,'VBN','O','O'),
     t((s\np)\ (s\np),out,out,'RP','O','O')))))).

ccg(116,
 ba(s:dcl,
  fa(np:nb,
   t(np:nb/n,'Every',every,'DT','O','O'),
   t(n,shirt,shirt,'NN','O','O')),
  fa(s:dcl\np,
   fa((s\np)/ (s\np),
    t(((s\np)/ (s\np))/np,in,in,'IN','O','O'),
    ba(np,
     lx(np, n,
      t(n,'Zara','Zara','NNP','O','I-LOC')),
     lx(np\np, s:dcl/np,
      fc(s:dcl/np,
       tr(s:_G441/ (s:_G447\np),
        t(np,'I',i,'PRP','O','O')),
       t((s:dcl\np)/np,liked,lik,'VBD','O','O'))))),
   ba(s:dcl\np,
    fa(s:dcl\np,
     t((s:dcl\np)/ (s:pss\np),is,be,'VBZ','O','O'),
     t(s:pss\np,sold,sell,'VBN','O','O')),
    t((s\np)\ (s\np),out,out,'RP','O','O'))))).

ccg(117,
 ba(s:dcl,
  ba(np,
   lx(np, n,
    fa(n,
     t(n/n,'Every',every,'DT','O','O'),
     t(n,shirt,shirt,'NN','O','O'))),
   fa(np\np,
    t((np\np)/np,in,in,'IN','O','O'),
    ba(np,
     lx(np, n,
      t(n,'Zara','Zara','NNP','O','I-LOC')),
     lx(np\np, s:dcl/np,
      fc(s:dcl/np,
       tr(s:_G324/ (s:_G330\np),
        t(np,'I',i,'PRP','O','O')),
       t((s:dcl\np)/np,liked,lik,'VBD','O','O')))))),
  ba(s:dcl\np,
   fa(s:dcl\np,
    t((s:dcl\np)/ (s:pss\np),is,be,'VBZ','O','O'),
    t(s:pss\np,sold,sell,'VBN','O','O')),
   t((s\np)\ (s\np),out,out,'RP','O','O')))).

ccg(118,
 ba(s:dcl,
  ba(np,
   lx(np, n,
    fa(n,
     t(n/n,'Every',every,'DT','O','O'),
     t(n,shirt,shirt,'NN','O','O'))),
   fa(np\np,
    t((np\np)/np,in,in,'IN','O','O'),
    ba(np,
     lx(np, n,
      t(n,'Zara','Zara','NNP','O','I-LOC')),
     lx(np\np, s:dcl/np,
      fc(s:dcl/np,
       tr(s:_G231/ (s:_G237\np),
        t(np,'I',i,'PRP','O','O')),
       t((s:dcl\np)/np,liked,lik,'VBD','O','O')))))),
  fa(s:dcl\np,
   t((s:dcl\np)/ (s:pss\np),is,be,'VBZ','O','O'),
   ba(s:pss\np,
    t(s:pss\np,sold,sell,'VBN','O','O'),
    t((s\np)\ (s\np),out,out,'RP','O','O'))))).

ccg(119,
 ba(s:dcl,
  ba(np,
   ba(np,
    lx(np, n,
     fa(n,
      t(n/n,'Every',every,'DT','O','O'),
      t(n,shirt,shirt,'NN','O','O'))),
    fa(np\np,
     t((np\np)/np,in,in,'IN','O','O'),
     lx(np, n,
      t(n,'Zara','Zara','NNP','O','I-LOC')))),
   lx(np\np, s:dcl/np,
    fc(s:dcl/np,
     tr(s:_G138/ (s:_G144\np),
      t(np,'I',i,'PRP','O','O')),
     t((s:dcl\np)/np,liked,lik,'VBD','O','O')))),
  fa(s:dcl\np,
   t((s:dcl\np)/ (s:pss\np),is,be,'VBZ','O','O'),
   ba(s:pss\np,
    t(s:pss\np,sold,sell,'VBN','O','O'),
    t((s\np)\ (s\np),out,out,'RP','O','O'))))).

ccg(120,
 ba(s:dcl,
  ba(np,
   ba(np,
    lx(np, n,
     fa(n,
      t(n/n,'Every',every,'DT','O','O'),
      t(n,shirt,shirt,'NN','O','O'))),
    fa(np\np,
     t((np\np)/np,in,in,'IN','O','O'),
     lx(np, n,
      t(n,'Zara','Zara','NNP','O','I-LOC')))),
   lx(np\np, s:dcl/np,
    fc(s:dcl/np,
     tr(s:_G45/ (s:_G51\np),
      t(np,'I',i,'PRP','O','O')),
     t((s:dcl\np)/np,liked,lik,'VBD','O','O')))),
  ba(s:dcl\np,
   fa(s:dcl\np,
    t((s:dcl\np)/ (s:pss\np),is,be,'VBZ','O','O'),
    t(s:pss\np,sold,sell,'VBN','O','O')),
   t((s\np)\ (s\np),out,out,'RP','O','O')))).



