:- op(601, xfx, (/)).
:- op(601, xfx, (\)).
:- multifile ccg/2, id/2.
:- discontiguous ccg/2, id/2.

ccg(1,
 ba(s:dcl,
  fa(np:nb,
   t(np:nb/n,a,a,'DT','O','O'),
   t(n,bird,bird,'NN','O','O')),
  t(s:dcl\np,flew,fly,'VBD','O','O'))).

ccg(2,
 ba(s:dcl,
  fa(np:nb,
   t(np:nb/n,a,a,'DT','O','O'),
   t(n,lark,lark,'NN','O','O')),
  t(s:dcl\np,flew,fly,'VBD','O','O'))).

ccg(3,
 ba(s:dcl,
  fa(np:nb,
   t(np:nb/n,a,a,'DT','O','O'),
   t(n,lark,lark,'NN','O','O')),
  t(s:dcl\np,flew,fly,'VBD','O','O'))).

ccg(4,
 ba(s:dcl,
  fa(np:nb,
   t(np:nb/n,a,a,'DT','O','O'),
   t(n,bird,bird,'NN','O','O')),
  t(s:dcl\np,moved,move,'VBD','O','O'))).

ccg(5,
 ba(s:dcl,
  ba(np:nb,
   fa(np:nb,
    t(np:nb/n,every,every,'DT','O','O'),
    t(n,person,person,'NN','O','O')),
   fa(np\np,
    t((np\np)/ (s:dcl/np),who,who,'WP','O','O'),
    fc(s:dcl/np,
     tr(s:_G9133/ (s:_G9139\np),
      lx(np, n,
       t(n,'Mary','Mary','NNP','O','I-PER'))),
     t((s:dcl\np)/np,touched,touch,'VBD','O','O')))),
  t(s:dcl\np,ran,run,'VBD','O','O'))).

ccg(6,
 ba(s:dcl,
  ba(np,
   lx(np, n,
    fa(n,
     t(n/n,most,most,'RBS','O','O'),
     t(n,students,student,'NNS','O','O'))),
   fa(np\np,
    t((np\np)/ (s:dcl/np),who,who,'WP','O','O'),
    fc(s:dcl/np,
     tr(s:_G9070/ (s:_G9076\np),
      lx(np, n,
       t(n,'Mary','Mary','NNP','O','I-PER'))),
     t((s:dcl\np)/np,kissed,kiss,'VBD','O','O')))),
  t(s:dcl\np,moved,move,'VBN','O','O'))).

ccg(7,
 ba(s:dcl,
  fa(np:nb,
   t(np:nb/n,no,no,'DT','O','O'),
   t(n,bird,bird,'NN','O','O')),
  t(s:dcl\np,moved,move,'VBD','O','O'))).

ccg(8,
 ba(s:dcl,
  fa(np:nb,
   t(np:nb/n,no,no,'DT','O','O'),
   t(n,lark,lark,'NN','O','O')),
  t(s:dcl\np,flew,fly,'VBD','O','O'))).

ccg(9,
 ba(s:dcl,
  lx(np, n,
   fa(n,
    t(n/n,'John','John','NNP','O','I-PER'),
    t(n,sleeps,sleep,'NNS','O','O'))),
  fa(s:dcl\np,
   t((s\np)/ (s\np),and,and,'CC','O','O'),
   fa(s:dcl\np,
    bxc((s:dcl\np)/ (s:b\np),
     t((s:dcl\np)/ (s:b\np),does,do,'VBZ','O','O'),
     t((s\np)\ (s\np),not,not,'RB','O','O')),
    t(s:b\np,sleep,sleep,'VB','O','O'))))).

ccg(10,
 ba(s:dcl,
  lx(np, n,
   t(n,'John','John','NNP','O','I-PER')),
  t(s:dcl\np,walks,walk,'VBZ','O','O'))).

ccg(11,
 fa(s:dcl,
  t(s:dcl/np,if,if,'IN','O','O'),
  ba(np,
   lx(np, n,
    fa(n,
     t(n/n,'John','John','NNP','O','I-PER'),
     t(n,sleeps,sleep,'VBZ','O','O'))),
   conj(np\np, np,
    t(',',',',',',',','O','O'),
    lx(np, n,
     fa(n,
      t(n/n,'John','John','NNP','O','I-PER'),
      t(n,snores,snore,'VBZ','O','O'))))))).

ccg(12,
 fa(s:dcl,
  fa(s/s,
   t((s/s)/s:dcl,if,if,'IN','O','O'),
   ba(s:dcl,
    lx(np, n,
     t(n,'John','John','NNP','O','I-PER')),
    fa(s:dcl\np,
     bxc((s:dcl\np)/ (s:b\np),
      t((s:dcl\np)/ (s:b\np),does,do,'VBZ','O','O'),
      t((s\np)\ (s\np),not,not,'RB','O','O')),
     rp(s:b\np,
      t(s:b\np,snore,snore,'VB','O','O'),
      t(',',',',',',',','O','O'))))),
  ba(s:dcl,
   lx(np, n,
    t(n,'John','John','NNP','O','I-PER')),
   fa(s:dcl\np,
    bxc((s:dcl\np)/ (s:b\np),
     t((s:dcl\np)/ (s:b\np),does,do,'VBZ','O','O'),
     t((s\np)\ (s\np),not,not,'RB','O','O')),
    t(s:b\np,sleep,sleep,'VB','O','O'))))).

ccg(13,
 fa(s:dcl,
  t(s:dcl/np,if,if,'IN','O','O'),
  ba(np,
   lx(np, n,
    fa(n,
     t(n/n,'John','John','NNP','O','I-PER'),
     t(n,sleeps,sleep,'VBZ','O','O'))),
   conj(np\np, np,
    t(',',',',',',',','O','O'),
    lx(np, n,
     fa(n,
      t(n/n,'John','John','NNP','O','I-PER'),
      t(n,snores,snore,'VBZ','O','O'))))))).

ccg(14,
 ba(s:dcl,
  ba(np,
   lx(np, n,
    fa(n,
     t(n/n,'John','John','NNP','O','I-PER'),
     t(n,snores,snore,'VBZ','O','O'))),
   conj(np\np, np,
    t(conj,or,or,'CC','O','O'),
    lx(np, n,
     t(n,'John','John','NNP','O','I-PER')))),
  fa(s:dcl\np,
   bxc((s:dcl\np)/ (s:b\np),
    t((s:dcl\np)/ (s:b\np),does,do,'VBZ','O','O'),
    t((s\np)\ (s\np),not,not,'RB','O','O')),
   t(s:b\np,sleep,sleep,'VB','O','O')))).

ccg(15,
 ba(s:dcl,
  lx(np, n,
   t(n,'John','John','NNP','O','I-PER')),
  t(s:dcl\np,snores,snore,'VBZ','O','O'))).

ccg(16,
 ba(s:dcl,
  lx(np, n,
   t(n,'John','John','NNP','O','I-PER')),
  t(s:dcl\np,sleeps,sleep,'VBZ','O','O'))).

ccg(17,
 ba(s:dcl,
  lx(np, n,
   fa(n,
    t(n/n,most,most,'RBS','O','O'),
    t(n,men,man,'NNS','O','O'))),
  t(s:dcl\np,walked,walk,'VBD','O','O'))).

ccg(18,
 ba(s:dcl,
  ba(s:dcl,
   lx(np, n,
    fa(n,
     t(n/n,most,most,'RBS','O','O'),
     t(n,men,man,'NNS','O','O'))),
   t(s:dcl\np,moved,move,'VBD','O','O')),
  conj(s:dcl\s:dcl, s:dcl,
   t(conj,or,or,'CC','O','O'),
   ba(s:dcl,
    fa(np:nb,
     t(np:nb/n,every,every,'DT','O','O'),
     t(n,woman,woman,'NN','O','O')),
    t(s:dcl\np,moved,move,'VBD','O','O'))))).

ccg(19,
 ba(s:dcl,
  fa(np:nb,
   t(np:nb/n,a,a,'DT','O','O'),
   t(n,bachelor,bachelor,'NN','O','O')),
  t(s:dcl\np,sleeps,sleep,'VBZ','O','O'))).

ccg(20,
 ba(s:dcl,
  ba(s:dcl,
   fa(np:nb,
    t(np:nb/n,a,a,'DT','O','O'),
    t(n,man,man,'NN','O','O')),
   t(s:dcl\np,sleeps,sleep,'VBZ','O','O')),
  conj(s:dcl\s:dcl, s:dcl,
   t(conj,or,or,'CC','O','O'),
   ba(s:dcl,
    lx(np, n,
     fa(n,
      t(n/n,few,few,'JJ','O','O'),
      t(n,humans,human,'NNS','O','O'))),
    t(s:dcl\np,sleep,sleep,'VBP','O','O'))))).

ccg(21,
 ba(s:dcl,
  fa(np:nb,
   t(np:nb/n,a,a,'DT','O','O'),
   t(n,bachelor,bachelor,'NN','O','O')),
  t(s:dcl\np,sleeps,sleep,'VBZ','O','O'))).

ccg(22,
 ba(s:dcl,
  fa(np:nb,
   t(np:nb/n,a,a,'DT','O','O'),
   t(n,man,man,'NN','O','O')),
  t(s:dcl\np,sleeps,sleep,'VBZ','O','O'))).

ccg(23,
 ba(s:dcl,
  fa(np:nb,
   t(np:nb/n,a,a,'DT','O','O'),
   t(n,dog,dog,'NN','O','O')),
  t(s:dcl\np,runs,run,'VBZ','O','O'))).

ccg(24,
 ba(s:dcl,
  ba(np:nb,
   fa(np:nb,
    t(np:nb/n,a,a,'DT','O','O'),
    fa(n,
     t(n/n,hound,hound,'JJ','O','O'),
     t(n,moves,move,'NNS','O','O'))),
   conj(np\np, np,
    t(conj,or,or,'CC','O','O'),
    lx(np, n,
     fa(n,
      t(n/n,most,most,'JJS','O','O'),
      t(n,animals,animal,'NNS','O','O'))))),
  t(s:dcl\np,run,run,'VBP','O','O'))).

ccg(25,
 ba(s:dcl,
  fa(np:nb,
   t(np:nb/n,a,a,'DT','O','O'),
   t(n,hound,hound,'NN','O','O')),
  t(s:dcl\np,runs,run,'VBZ','O','O'))).

ccg(26,
 ba(s:dcl,
  ba(np:nb,
   fa(np:nb,
    t(np:nb/n,a,a,'DT','O','O'),
    fa(n,
     t(n/n,dog,dog,'NN','O','O'),
     t(n,runs,run,'VBZ','O','O'))),
   conj(np\np, np,
    t(conj,or,or,'CC','O','O'),
    lx(np, n,
     fa(n,
      t(n/n,most,most,'JJS','O','O'),
      t(n,animals,animal,'NNS','O','O'))))),
  t(s:dcl\np,run,run,'VBP','O','O'))).

ccg(27,
 ba(s:dcl,
  fa(np:nb,
   t(np:nb/n,a,a,'DT','O','O'),
   t(n,dog,dog,'NN','O','O')),
  t(s:dcl\np,runs,run,'VBZ','O','O'))).

ccg(28,
 ba(s:dcl,
  ba(s:dcl,
   fa(np:nb,
    t(np:nb/n,a,a,'DT','O','O'),
    t(n,man,man,'NN','O','O')),
   t(s:dcl\np,moves,move,'VBZ','O','O')),
  conj(s:dcl\s:dcl, s:dcl,
   t(conj,or,or,'CC','O','O'),
   ba(s:dcl,
    lx(np, n,
     fa(n,
      t(n/n,most,most,'JJS','O','O'),
      t(n,animals,animal,'NNS','O','O'))),
    t(s:dcl\np,sleep,sleep,'VBP','O','O'))))).

ccg(29,
 ba(s:dcl,
  ba(np:nb,
   fa(np:nb,
    t(np:nb/n,a,a,'DT','O','O'),
    fa(n,
     t(n/n,dog,dog,'NN','O','O'),
     t(n,runs,run,'VBZ','O','O'))),
   conj(np:nb\np:nb, np:nb,
    t(conj,and,and,'CC','O','O'),
    fa(np:nb,
     t(np:nb/n,a,a,'DT','O','O'),
     t(n,bachelor,bachelor,'NN','O','O')))),
  t(s:dcl\np,sleeps,sleep,'VBZ','O','O'))).

ccg(30,
 ba(s:dcl,
  fa(np:nb,
   t(np:nb/n,a,a,'DT','O','O'),
   t(n,man,man,'NN','O','O')),
  t(s:dcl\np,sleeps,sleep,'VBZ','O','O'))).

ccg(31,
 ba(s:dcl,
  ba(np:nb,
   fa(np:nb,
    t(np:nb/n,a,a,'DT','O','O'),
    fa(n,
     t(n/n,bachelor,bachelor,'NN','O','O'),
     t(n,sleeps,sleep,'VBZ','O','O'))),
   conj(np:nb\np:nb, np:nb,
    t(conj,and,and,'CC','O','O'),
    fa(np:nb,
     t(np:nb/n,a,a,'DT','O','O'),
     t(n,dog,dog,'NN','O','O')))),
  t(s:dcl\np,runs,run,'VBZ','O','O'))).

ccg(32,
 ba(s:dcl,
  fa(np:nb,
   t(np:nb/n,a,a,'DT','O','O'),
   t(n,man,man,'NN','O','O')),
  t(s:dcl\np,sleeps,sleep,'VBZ','O','O'))).

ccg(33,
 ba(s:dcl,
  lx(np, n,
   t(n,'John','John','NNP','O','I-PER')),
  t(s:dcl\np,sleeps,sleep,'VBZ','O','O'))).

ccg(34,
 ba(s:dcl,
  fa(np:nb,
   t(np:nb/n,a,a,'DT','O','O'),
   t(n,man,man,'NN','O','O')),
  t(s:dcl\np,sleeps,sleep,'VBZ','O','O'))).

ccg(35,
 ba(s:dcl,
  ba(np,
   lx(np, n,
    fa(n,
     t(n/n,'John','John','NNP','O','I-PER'),
     t(n,sleeps,sleep,'VBZ','O','O'))),
   conj(np\np, np,
    t(conj,and,and,'CC','O','O'),
    lx(np, n,
     t(n,'Mary','Mary','NNP','O','I-PER')))),
  t(s:dcl\np,sleeps,sleep,'NNS','O','O'))).

ccg(36,
 ba(s:dcl,
  ba(s:dcl,
   fa(np:nb,
    t(np:nb/n,a,a,'DT','O','O'),
    t(n,man,man,'NN','O','O')),
   t(s:dcl\np,sleeps,sleep,'VBZ','O','O')),
  conj(s:dcl\s:dcl, s:dcl,
   t(conj,and,and,'CC','O','O'),
   ba(s:dcl,
    fa(np:nb,
     t(np:nb/n,a,a,'DT','O','O'),
     t(n,woman,woman,'NN','O','O')),
    t(s:dcl\np,sleeps,sleep,'VBZ','O','O'))))).

ccg(37,
 ba(s:dcl,
  lx(np, n,
   t(n,'John','John','NNP','O','I-PER')),
  t(s:dcl\np,sleeps,sleep,'VBZ','O','O'))).

ccg(38,
 ba(s:dcl,
  fa(np:nb,
   t(np:nb/n,a,a,'DT','O','O'),
   t(n,person,person,'NN','O','O')),
  t(s:dcl\np,sleeps,sleep,'VBZ','O','O'))).

ccg(39,
 ba(s:dcl,
  fa(np:nb,
   t(np:nb/n,no,no,'DT','O','O'),
   t(n,person,person,'NN','O','O')),
  t(s:dcl\np,sleeps,sleep,'VBZ','O','O'))).

ccg(40,
 ba(s:dcl,
  lx(np, n,
   t(n,'John','John','NNP','O','I-PER')),
  fa(s:dcl\np,
   bxc((s:dcl\np)/ (s:b\np),
    t((s:dcl\np)/ (s:b\np),does,do,'VBZ','O','O'),
    t((s\np)\ (s\np),not,not,'RB','O','O')),
   t(s:b\np,sleep,sleep,'VB','O','O')))).

ccg(41,
 ba(s:dcl,
  ba(s:dcl,
   fa(np:nb,
    t(np:nb/n,every,every,'DT','O','O'),
    t(n,man,man,'NN','O','O')),
   t(s:dcl\np,walks,walk,'VBZ','O','O')),
  conj(s:dcl\s:dcl, s:dcl,
   t(conj,and,and,'CC','O','O'),
   ba(s:dcl,
    fa(np:nb,
     t(np:nb/n,no,no,'DT','O','O'),
     t(n,human,human,'NN','O','O')),
    t(s:dcl\np,flies,fly,'VBZ','O','O'))))).

ccg(42,
 ba(s:dcl,
  ba(np,
   lx(np, n,
    fa(n,
     t(n/n,'John','John','NNP','O','I-PER'),
     t(n,walks,walk,'VBZ','O','O'))),
   conj(np\np, np,
    t(conj,and,and,'CC','O','O'),
    lx(np, n,
     t(n,'Mary','Mary','NNP','O','I-PER')))),
  fa(s:dcl\np,
   bxc((s:dcl\np)/ (s:b\np),
    t((s:dcl\np)/ (s:b\np),does,do,'VBZ','O','O'),
    t((s\np)\ (s\np),not,not,'RB','O','O')),
   t(s:b\np,fly,fly,'VB','O','O')))).

ccg(43,
 ba(s:dcl,
  fa(np:nb,
   t(np:nb/n,every,every,'DT','O','O'),
   t(n,man,man,'NN','O','O')),
  t(s:dcl\np,walks,walk,'VBZ','O','O'))).

ccg(44,
 ba(s:dcl,
  lx(np, n,
   t(n,'John','John','NNP','O','I-PER')),
  t(s:dcl\np,walks,walk,'VBZ','O','O'))).

ccg(45,
 ba(s:dcl,
  ba(np:nb,
   fa(np:nb,
    t(np:nb/n,no,no,'DT','O','O'),
    fa(n,
     t(n/n,human,human,'NN','O','O'),
     t(n,flies,fly,'VBZ','O','O'))),
   conj(np:nb\np:nb, np:nb,
    t(conj,and,and,'CC','O','O'),
    fa(np:nb,
     t(np:nb/n,every,every,'DT','O','O'),
     t(n,man,man,'NN','O','O')))),
  t(s:dcl\np,walks,walk,'VBZ','O','O'))).

ccg(46,
 ba(s:dcl,
  lx(np, n,
   t(n,'John','John','NNP','O','I-PER')),
  t(s:dcl\np,walks,walk,'VBZ','O','O'))).

ccg(47,
 ba(s:dcl,
  fa(np:nb,
   t(np:nb/n,a,a,'DT','O','O'),
   t(n,man,man,'NN','O','O')),
  t(s:dcl\np,walks,walk,'VBZ','O','O'))).

ccg(48,
 ba(s:dcl,
  fa(np:nb,
   t(np:nb/n,a,a,'DT','O','O'),
   t(n,woman,woman,'NN','O','O')),
  fa(s:dcl\np,
   bxc((s:dcl\np)/ (s:b\np),
    t((s:dcl\np)/ (s:b\np),does,do,'VBZ','O','O'),
    t((s\np)\ (s\np),not,not,'RB','O','O')),
   fa(s:b\np,
    t((s:b\np)/np,kiss,kiss,'VB','O','O'),
    fa(np:nb,
     t(np:nb/n,a,a,'DT','O','O'),
     t(n,student,student,'NN','O','O')))))).

ccg(49,
 ba(s:dcl,
  fa(np:nb,
   t(np:nb/n,a,a,'DT','O','O'),
   t(n,man,man,'NN','O','O')),
  t(s:dcl\np,walked,walk,'VBD','O','O'))).

ccg(50,
 ba(s:dcl,
  ba(np:nb,
   fa(np:nb,
    t(np:nb/n,a,a,'DT','O','O'),
    t(n,woman,woman,'NN','O','O')),
   fa(np\np,
    t((np\np)/ (s:dcl\np),who,who,'WP','O','O'),
    fa(s:dcl\np,
     bxc((s:dcl\np)/ (s:b\np),
      t((s:dcl\np)/ (s:b\np),did,do,'VBD','O','O'),
      t((s\np)\ (s\np),not,not,'RB','O','O')),
     fa(s:b\np,
      t((s:b\np)/np,kiss,kiss,'VB','O','O'),
      fa(np:nb,
       t(np:nb/n,a,a,'DT','O','O'),
       t(n,student,student,'NN','O','O')))))),
  t(s:dcl\np,walked,walk,'VBD','O','O'))).

ccg(51,
 ba(s:dcl,
  fa(np:nb,
   t(np:nb/n,every,every,'DT','O','O'),
   t(n,man,man,'NN','O','O')),
  fa(s:dcl\np,
   fa((s:dcl\np)/np,
    t(((s:dcl\np)/np)/np,gave,give,'VBD','O','O'),
    fa(np:nb,
     t(np:nb/n,every,every,'DT','O','O'),
     t(n,woman,woman,'NN','O','O'))),
   fa(np:nb,
    t(np:nb/n,a,a,'DT','O','O'),
    t(n,book,book,'NN','O','O'))))).

ccg(52,
 ba(s:dcl,
  lx(np, n,
   t(n,'John','John','NNP','O','I-PER')),
  fa(s:dcl\np,
   fa((s:dcl\np)/np,
    t(((s:dcl\np)/np)/np,gave,give,'VBD','O','O'),
    lx(np, n,
     t(n,'Emily','Emily','RB','O','I-PER'))),
   fa(np:nb,
    t(np:nb/n,a,a,'DT','O','O'),
    t(n,book,book,'NN','O','O'))))).

ccg(53,
 ba(s:dcl,
  fa(np:nb,
   t(np:nb/n,every,every,'DT','O','O'),
   t(n,man,man,'NN','O','O')),
  fa(s:dcl\np,
   fa((s:dcl\np)/np,
    t(((s:dcl\np)/np)/np,gave,give,'VBD','O','O'),
    fa(np:nb,
     t(np:nb/n,every,every,'DT','O','O'),
     t(n,woman,woman,'NN','O','O'))),
   fa(np:nb,
    t(np:nb/n,a,a,'DT','O','O'),
    t(n,book,book,'NN','O','O'))))).

ccg(54,
 ba(s:dcl,
  lx(np, n,
   t(n,'John','John','NNP','O','I-PER')),
  fa(s:dcl\np,
   bxc((s:dcl\np)/np,
    t(((s:dcl\np)/np)/np,gave,give,'VBD','O','O'),
    tr((s:_G4597\np)\ ((s:_G4606\np)/np),
     lx(np, n,
      t(n,'Kate','Kate','NNP','O','I-PER')))),
   fa(np:nb,
    t(np:nb/n,a,a,'DT','O','O'),
    t(n,book,book,'NN','O','O'))))).

ccg(55,
 ba(s:dcl,
  t(np,you,you,'PRP','O','O'),
  fa(s:dcl\np,
   bxc((s:dcl\np)/ (s:b\np),
    t((s:dcl\np)/ (s:b\np),shall,shall,'MD','O','O'),
    t((s\np)\ (s\np),not,not,'RB','O','O')),
   t(s:b\np,lie,lie,'VB','O','O')))).

ccg(56,
 ba(s:dcl,
  t(np,you,you,'PRP','O','O'),
  t(s:dcl\np,lie,lie,'VBP','O','O'))).

ccg(57,
 ba(s:dcl,
  fa(np:nb,
   t(np:nb/n,'Every','Every','DT','O','O'),
   fa(n,
    t(n/n,male,male,'NN','O','O'),
    t(n,scientist,scientist,'NN','O','O'))),
  fa(s:dcl\np,
   t((s:dcl\np)/np,is,be,'VBZ','O','O'),
   fa(np:nb,
    t(np:nb/n,a,a,'DT','O','O'),
    t(n,man,man,'NN','O','O'))))).

ccg(58,
 ba(s:dcl,
  fa(np:nb,
   t(np:nb/n,'Every','Every','DT','O','O'),
   t(n,man,man,'NN','O','O')),
  fa(s:dcl\np,
   t((s:dcl\np)/np,is,be,'VBZ','O','O'),
   fa(np:nb,
    t(np:nb/n,a,a,'DT','O','O'),
    fa(n,
     t(n/n,male,male,'JJ','O','O'),
     t(n,person,person,'NN','O','O')))))).

ccg(59,
 ba(s:dcl,
  fa(np:nb,
   t(np:nb/n,'A','A','DT','O','O'),
   fa(n,
    t(n/n,male,male,'JJ','O','O'),
    t(n,scientist,scientist,'NN','O','O'))),
  fa(s:dcl\np,
   t((s:dcl\np)/np,is,be,'VBZ','O','O'),
   fa(np:nb,
    t(np:nb/n,a,a,'DT','O','O'),
    fa(n,
     t(n/n,male,male,'JJ','O','O'),
     t(n,person,person,'NN','O','O')))))).

ccg(60,
 ba(s:dcl,
  ba(np,
   lx(np, n,
    fa(n,
     t(n/n,'John','John','NNP','O','I-PER'),
     t(n,slept,sleep,'VBD','O','O'))),
   conj(np:nb\np:nb, np:nb,
    t(conj,and,and,'CC','O','O'),
    fa(np:nb,
     t(np:nb/n,no,no,'DT','O','O'),
     t(n,man,man,'NN','O','O')))),
  t(s:dcl\np,snored,snore,'VBD','O','O'))).

ccg(61,
 ba(s:dcl,
  ba(np:nb,
   ba(np:nb,
    fa(np:nb,
     t(np:nb/n,no,no,'DT','O','O'),
     t(n,man,man,'NN','O','O')),
    lx(np\np, s:pss\np,
     t(s:pss\np,snored,snore,'VBN','O','O'))),
   conj(np\np, np,
    t(conj,and,and,'CC','O','O'),
    lx(np, n,
     t(n,'John','John','NNP','O','I-PER')))),
  t(s:dcl\np,slept,sleep,'VBD','O','O'))).

ccg(62,
 ba(s:dcl,
  lx(np, n,
   ba(n,
    fa(n,
     t(n/n,small,small,'JJ','O','O'),
     t(n,bird,bird,'NN','O','O')),
    t(n\n,that,that,'WDT','O','O'))),
  t(s:dcl\np,moved,move,'VBD','O','O'))).

ccg(63,
 ba(s:dcl,
  lx(np, n,
   t(n,small,small,'JJ','O','O')),
  t(s:dcl\np,bird,bird,'NN','O','O'))).

ccg(64,
 ba(s:dcl,
  t(np:thr,there,there,'EX','O','O'),
  fa(s:dcl\np:thr,
   t((s:dcl\np:thr)/np,is,be,'VBZ','O','O'),
   ba(np:nb,
    fa(np:nb,
     t(np:nb/n,a,a,'DT','O','O'),
     t(n,girl,girl,'NN','O','O')),
    fa(np\np,
     t((np\np)/ (s:dcl\np),who,who,'WP','O','O'),
     t(s:dcl\np,smokes,smoke,'VBZ','O','O')))))).

ccg(65,
 ba(s:dcl,
  fa(np:nb,
   t(np:nb/n,a,a,'DT','O','O'),
   t(n,person,person,'NN','O','O')),
  t(s:dcl\np,smokes,smoke,'VBZ','O','O'))).

ccg(66,
 ba(s:dcl,
  ba(np:nb,
   fa(np:nb,
    t(np:nb/n,the,the,'DT','O','O'),
    t(n,man,man,'NN','O','O')),
   fa(np\np,
    t((np\np)/ (s:dcl\np),that,that,'IN','O','O'),
    t(s:dcl\np,smokes,smoke,'NNS','O','O'))),
  fa(s:dcl\np,
   t((s:dcl\np)/np,is,be,'VBZ','O','O'),
   lx(np, n,
    t(n,'John','John','NNP','O','I-PER'))))).

ccg(67,
 ba(s:dcl,
  t(np:thr,there,there,'EX','O','O'),
  fa(s:dcl\np:thr,
   t((s:dcl\np:thr)/np,is,be,'VBZ','O','O'),
   ba(np:nb,
    fa(np:nb,
     t(np:nb/n,a,a,'DT','O','O'),
     t(n,person,person,'NN','O','O')),
    fa(np\np,
     t((np\np)/ (s:dcl\np),who,who,'WP','O','O'),
     t(s:dcl\np,smokes,smoke,'VBZ','O','O')))))).

ccg(68,
 ba(s:dcl,
  fa(np:nb,
   t(np:nb/n,a,a,'DT','O','O'),
   fa(n,
    t(n/n,beautiful,beautiful,'JJ','O','O'),
    t(n,dance,dance,'NN','O','O'))),
  fa(s:dcl\np,
   t((s:dcl\np)/ (s:pss\np),was,be,'VBD','O','O'),
   ba(s:pss\np,
    t(s:pss\np,performed,perform,'VBN','O','O'),
    fa((s\np)\ (s\np),
     t(((s\np)\ (s\np))/np,by,by,'IN','O','O'),
     lx(np, n,
      t(n,'Mary','Mary','NNP','O','I-PER'))))))).

ccg(69,
 ba(s:dcl,
  lx(np, n,
   t(n,'Mary','Mary','NNP','O','I-PER')),
  ba(s:dcl\np,
   t(s:dcl\np,danced,dance,'VBD','O','O'),
   t((s\np)\ (s\np),beautifully,beautifully,'RB','O','O')))).

ccg(70,
 ba(s:dcl,
  fa(np:nb,
   t(np:nb/n,a,a,'DT','O','O'),
   fa(n,
    t(n/n,beautiful,beautiful,'JJ','O','O'),
    t(n,dance,dance,'NN','O','O'))),
  fa(s:dcl\np,
   t((s:dcl\np)/ (s:pss\np),was,be,'VBD','O','O'),
   ba(s:pss\np,
    t(s:pss\np,performed,perform,'VBN','O','O'),
    fa((s\np)\ (s\np),
     t(((s\np)\ (s\np))/np,by,by,'IN','O','O'),
     lx(np, n,
      t(n,'Mary','Mary','NNP','O','I-PER'))))))).

ccg(71,
 ba(s:dcl,
  lx(np, n,
   t(n,'Mary','Mary','NNP','O','I-PER')),
  t(s:dcl\np,danced,dance,'VBD','O','O'))).

ccg(72,
 ba(s:dcl,
  fa(np:nb,
   t(np:nb/n,a,a,'DT','O','O'),
   fa(n,
    t(n/n,beautiful,beautiful,'JJ','O','O'),
    t(n,dance,dance,'NN','O','O'))),
  fa(s:dcl\np,
   t((s:dcl\np)/ (s:pss\np),was,be,'VBD','O','O'),
   ba(s:pss\np,
    t(s:pss\np,done,do,'VBN','O','O'),
    fa((s\np)\ (s\np),
     t(((s\np)\ (s\np))/np,by,by,'IN','O','O'),
     lx(np, n,
      t(n,'Mary','Mary','NNP','O','I-PER'))))))).

ccg(73,
 ba(s:dcl,
  lx(np, n,
   t(n,'Mary','Mary','NNP','O','I-PER')),
  fa(s:dcl\np,
   t((s\np)/ (s\np),beautifully,beautifully,'RB','O','O'),
   t(s:dcl\np,danced,dance,'VBD','O','O')))).

ccg(74,
 ba(s:dcl,
  fa(np:nb,
   t(np/np,not,not,'RB','O','O'),
   fa(np:nb,
    t(np:nb/n,all,all,'DT','O','O'),
    t(n,birds,bird,'NNS','O','O'))),
  t(s:dcl\np,fly,fly,'VBP','O','O'))).

ccg(75,
 ba(s:dcl,
  fa(np:nb,
   t(np:nb/n,some,some,'DT','O','O'),
   t(n,birds,bird,'NNS','O','O')),
  fa(s:dcl\np,
   bxc((s:dcl\np)/ (s:b\np),
    t((s:dcl\np)/ (s:b\np),do,do,'VBP','O','O'),
    t((s\np)\ (s\np),not,not,'RB','O','O')),
   t(s:b\np,fly,fly,'VB','O','O')))).

ccg(76,
 ba(s:dcl,
  fa(np,
   t(np/np,not,not,'RB','O','O'),
   t(np,everybody,everybody,'DT','O','O')),
  fa(s:dcl\np,
   t((s:dcl\np)/ (s:ng\np),is,be,'VBZ','O','O'),
   t(s:ng\np,dancing,dance,'VBG','O','O')))).

ccg(77,
 ba(s:dcl,
  t(np,somebody,somebody,'DT','O','O'),
  fa(s:dcl\np,
   bxc((s:dcl\np)/ (s:ng\np),
    t((s:dcl\np)/ (s:ng\np),is,be,'VBZ','O','O'),
    t((s\np)\ (s\np),not,not,'RB','O','O')),
   t(s:ng\np,dancing,dance,'VBG','O','O')))).

ccg(78,
 ba(s:dcl,
  fa(np:nb,
   t(np:nb/n,every,every,'DT','O','O'),
   t(n,king,king,'NN','O','O')),
  fa(s:dcl\np,
   t((s:dcl\np)/np,is,be,'VBZ','O','O'),
   fa(np:nb,
    t(np:nb/n,a,a,'DT','O','O'),
    t(n,man,man,'NN','O','O'))))).

ccg(79,
 ba(s:dcl,
  ba(np,
   t(np,'Everyone','Everyone','DT','O','O'),
   fa(np\np,
    t((np\np)/ (s:dcl\np),who,who,'WP','O','O'),
    fa(s:dcl\np,
     t((s:dcl\np)/np,sees,see,'VBZ','O','O'),
     fa(np:nb,
      t(np:nb/n,all,all,'DT','O','O'),
      t(n,men,man,'NNS','O','O'))))),
  fa(s:dcl\np,
   t((s:dcl\np)/np,sees,see,'VBZ','O','O'),
   fa(np:nb,
    t(np:nb/n,all,all,'DT','O','O'),
    t(n,kings,king,'NNS','O','O'))))).

ccg(80,
 ba(s:dcl,
  fa(np:nb,
   t(np:nb/n,every,every,'DT','O','O'),
   t(n,king,king,'NN','O','O')),
  fa(s:dcl\np,
   t((s:dcl\np)/np,is,be,'VBZ','O','O'),
   fa(np:nb,
    t(np:nb/n,a,a,'DT','O','O'),
    t(n,man,man,'NN','O','O'))))).

ccg(81,
 ba(s:dcl,
  ba(np,
   t(np,'Everyone','Everyone','DT','O','O'),
   fa(np\np,
    t((np\np)/ (s:dcl\np),who,who,'WP','O','O'),
    fa(s:dcl\np,
     t((s:dcl\np)/np,sees,see,'VBZ','O','O'),
     fa(np:nb,
      t(np:nb/n,all,all,'DT','O','O'),
      t(n,men,man,'NNS','O','O'))))),
  fa(s:dcl\np,
   t((s:dcl\np)/np,sees,see,'VBZ','O','O'),
   fa(np:nb,
    t(np:nb/n,all,all,'DT','O','O'),
    t(n,kings,king,'NNS','O','O'))))).

ccg(82,
 ba(s:dcl,
  fa(np:nb,
   t(np:nb/n,'A','A','DT','O','O'),
   t(n,man,man,'NN','O','O')),
  fa(s:dcl\np,
   t((s:dcl\np)/ (s:ng\np),is,be,'VBZ','O','O'),
   ba(s:ng\np,
    t(s:ng\np,walking,walk,'VBG','O','O'),
    fa((s\np)\ (s\np),
     t(((s\np)\ (s\np))/np,on,on,'IN','O','O'),
     fa(np:nb,
      t(np:nb/n,the,the,'DT','O','O'),
      t(n,beach,beach,'NN','O','O'))))))).

ccg(83,
 ba(s:dcl,
  fa(np:nb,
   t(np:nb/n,'A','A','DT','O','O'),
   t(n,man,man,'NN','O','O')),
  fa(s:dcl\np,
   t((s:dcl\np)/pp,is,be,'VBZ','O','O'),
   fa(pp,
    t(pp/np,on,on,'IN','O','O'),
    fa(np:nb,
     t(np:nb/n,a,a,'DT','O','O'),
     t(n,beach,beach,'NN','O','O')))))).

ccg(84,
 ba(s:dcl,
  ba(np:nb,
   fa(np:nb,
    t(np:nb/n,'A','A','DT','O','O'),
    t(n,group,group,'NN','O','O')),
   fa(np\np,
    t((np\np)/np,of,of,'IN','O','O'),
    lx(np, n,
     t(n,boys,boy,'NNS','O','O')))),
  fa(s:dcl\np,
   t((s:dcl\np)/ (s:ng\np),is,be,'VBZ','O','O'),
   t(s:ng\np,walking,walk,'VBG','O','O')))).

ccg(85,
 ba(s:dcl,
  fa(np:nb,
   t(np:nb/n,'Some','Some','DT','O','O'),
   t(n,boys,boy,'NNS','O','O')),
  fa(s:dcl\np,
   t((s:dcl\np)/ (s:ng\np),are,be,'VBP','O','O'),
   t(s:ng\np,walking,walk,'VBG','O','O')))).

ccg(86,
 ba(s:dcl,
  lx(np, n,
   fa(n,
    t(n/n,'Several','Several','JJ','O','O'),
    t(n,boys,boy,'NNS','O','O'))),
  fa(s:dcl\np,
   t((s:dcl\np)/ (s:ng\np),are,be,'VBP','O','O'),
   t(s:ng\np,walking,walk,'VBG','O','O')))).

ccg(87,
 ba(s:dcl,
  ba(np:nb,
   fa(np:nb,
    t(np:nb/n,'A','A','DT','O','O'),
    t(n,group,group,'NN','O','O')),
   fa(np\np,
    t((np\np)/np,of,of,'IN','O','O'),
    lx(np, n,
     t(n,boys,boy,'NNS','O','O')))),
  fa(s:dcl\np,
   t((s:dcl\np)/ (s:ng\np),is,be,'VBZ','O','O'),
   t(s:ng\np,walking,walk,'VBG','O','O')))).

ccg(88,
 ba(s:dcl,
  fa(np:nb,
   t(np:nb/n,'A','A','DT','O','O'),
   t(n,grass,grass,'NN','O','O')),
  fa(s:dcl\np,
   t((s:dcl\np)/ (s:adj\np),is,be,'VBZ','O','O'),
   t(s:adj\np,wet,wet,'JJ','O','O')))).

ccg(89,
 ba(s:dcl,
  fa(np:nb,
   t(np:nb/n,'A','A','DT','O','O'),
   t(n,person,person,'NN','O','O')),
  fa(s:dcl\np,
   t((s:dcl\np)/ (s:adj\np),is,be,'VBZ','O','O'),
   t(s:adj\np,wet,wet,'JJ','O','O')))).

ccg(90,
 ba(s:dcl,
  ba(np:nb,
   fa(np:nb,
    t(np:nb/n,'Every','Every','DT','O','O'),
    t(n,owner,owner,'NN','O','O')),
   fa(np\np,
    t((np\np)/np,of,of,'IN','O','O'),
    fa(np:nb,
     t(np:nb/n,a,a,'DT','O','O'),
     t(n,firm,firm,'NN','O','O')))),
  fa(s:dcl\np,
   t((s:dcl\np)/pp,is,be,'VBZ','O','O'),
   fa(pp,
    t(pp/np,in,in,'IN','O','O'),
    fa(np:nb,
     t(np:nb/n,a,a,'DT','O','O'),
     t(n,pub,pub,'NN','O','O')))))).

ccg(91,
 fa(s:dcl,
  fa(s/s,
   t((s/s)/np,'In','In','IN','O','O'),
   rp(np:nb,
    fa(np:nb,
     t(np:nb/n,a,a,'DT','O','O'),
     t(n,pub,pub,'NN','O','O')),
    t(',',',',',',',','O','O'))),
  ba(s:dcl,
   t(np:thr,there,there,'EX','O','O'),
   fa(s:dcl\np:thr,
    t((s:dcl\np:thr)/np,is,be,'VBZ','O','O'),
    ba(np:nb,
     fa(np:nb,
      t(np:nb/n,every,every,'DT','O','O'),
      t(n,owner,owner,'NN','O','O')),
     fa(np\np,
      t((np\np)/np,of,of,'IN','O','O'),
      fa(np:nb,
       t(np:nb/n,a,a,'DT','O','O'),
       t(n,firm,firm,'NN','O','O')))))))).

ccg(92,
 ba(s:dcl,
  ba(np:nb,
   fa(np:nb,
    t(np:nb/n,'Every','Every','DT','O','O'),
    t(n,owner,owner,'NN','O','O')),
   fa(np\np,
    t((np\np)/np,of,of,'IN','O','O'),
    fa(np:nb,
     t(np:nb/n,a,a,'DT','O','O'),
     t(n,firm,firm,'NN','O','O')))),
  fa(s:dcl\np,
   t((s:dcl\np)/pp,is,be,'VBZ','O','O'),
   fa(pp,
    t(pp/np,in,in,'IN','O','O'),
    ba(np:nb,
     fa(np:nb,
      t(np:nb/n,a,a,'DT','O','O'),
      t(n,pub,pub,'NN','O','O')),
     fa(np\np,
      t((np\np)/ (s:dcl/np),which,which,'WDT','O','O'),
      fc(s:dcl/np,
       tr(s:_G2926/ (s:_G2932\np),
        t(np,everybody,everybody,'DT','O','O')),
       t((s:dcl\np)/np,likes,likes,'NN','O','O')))))))).

ccg(93,
 ba(s:dcl,
  ba(np:nb,
   fa(np:nb,
    t(np:nb/n,'Every','Every','DT','O','O'),
    t(n,owner,owner,'NN','O','O')),
   fa(np\np,
    t((np\np)/np,of,of,'IN','O','O'),
    fa(np:nb,
     t(np:nb/n,a,a,'DT','O','O'),
     t(n,firm,firm,'NN','O','O')))),
  fa(s:dcl\np,
   t((s:dcl\np)/pp,is,be,'VBZ','O','O'),
   fa(pp,
    t(pp/np,in,in,'IN','O','O'),
    ba(np:nb,
     fa(np:nb,
      t(np:nb/n,a,a,'DT','O','O'),
      t(n,pub,pub,'NN','O','O')),
     fa(np\np,
      t((np\np)/ (s:dcl\np),which,which,'WDT','O','O'),
      fa(s:dcl\np,
       t((s:dcl\np)/ (s:pss\np),is,be,'VBZ','O','O'),
       ba(s:pss\np,
        t(s:pss\np,built,build,'VBN','O','O'),
        fa((s\np)\ (s\np),
         t(((s\np)\ (s\np))/np,by,by,'IN','O','O'),
         t(np,somebody,somebody,'DT','O','O')))))))))).

ccg(94,
 ba(s:dcl,
  ba(np:nb,
   fa(np:nb,
    t(np:nb/n,'Every','Every','DT','O','O'),
    t(n,man,man,'NN','O','O')),
   fa(np\np,
    t((np\np)/ (s:dcl\np),who,who,'WP','O','O'),
    fa(s:dcl\np,
     t((s:dcl\np)/np,ate,eat,'VBD','O','O'),
     fa(np:nb,
      t(np:nb/n,a,a,'DT','O','O'),
      t(n,burger,burger,'NN','O','O'))))),
  fa(s:dcl\np,
   t((s:dcl\np)/pp,is,be,'VBZ','O','O'),
   fa(pp,
    t(pp/np,in,in,'IN','O','O'),
    fa(np:nb,
     t(np:nb/n,a,a,'DT','O','O'),
     t(n,hospital,hospital,'NN','O','O')))))).

ccg(95,
 ba(s:dcl,
  ba(np:nb,
   fa(np:nb,
    t(np:nb/n,'Every','Every','DT','O','O'),
    fa(n,
     t(n/n,old,old,'JJ','O','O'),
     t(n,man,man,'NN','O','O'))),
   fa(np\np,
    t((np\np)/ (s:dcl\np),who,who,'WP','O','O'),
    fa(s:dcl\np,
     t((s:dcl\np)/np,ate,eat,'VBD','O','O'),
     ba(np:nb,
      fa(np:nb,
       t(np:nb/n,a,a,'DT','O','O'),
       t(n,burger,burger,'NN','O','O')),
      conj(np:nb\np:nb, np:nb,
       t(conj,and,and,'CC','O','O'),
       fa(np:nb,
        t(np:nb/n,a,a,'DT','O','O'),
        t(n,sandwich,sandwich,'NN','O','O'))))))),
  fa(s:dcl\np,
   t((s:dcl\np)/pp,is,be,'VBZ','O','O'),
   fa(pp,
    t(pp/np,in,in,'IN','O','O'),
    fa(np:nb,
     t(np:nb/n,a,a,'DT','O','O'),
     t(n,hospital,hospital,'NN','O','O')))))).

ccg(96,
 ba(s:dcl,
  ba(s:dcl,
   fa(np:nb,
    t(np:nb/n,'Every','Every','DT','O','O'),
    t(n,man,man,'NN','O','O')),
   fa(s:dcl\np,
    t((s:dcl\np)/ (s:ng\np),is,be,'VBZ','O','O'),
    t(s:ng\np,running,run,'VBG','O','O'))),
  conj(s:dcl\s:dcl, s:dcl,
   t(conj,and,and,'CC','O','O'),
   ba(s:dcl,
    lx(np, n,
     t(n,'Mary','Mary','NNP','O','I-PER')),
    fa(s:dcl\np,
     t((s:dcl\np)/ (s:ng\np),is,be,'VBZ','O','O'),
     t(s:ng\np,sleeping,sleep,'VBG','O','O')))))).

ccg(97,
 ba(s:dcl,
  ba(s:dcl,
   fa(np:nb,
    t(np:nb/n,'Every','Every','DT','O','O'),
    t(n,man,man,'NN','O','O')),
   fa(s:dcl\np,
    t((s:dcl\np)/ (s:ng\np),is,be,'VBZ','O','O'),
    t(s:ng\np,running,run,'VBG','O','O'))),
  conj(s:dcl\s:dcl, s:dcl,
   t(conj,and,and,'CC','O','O'),
   ba(s:dcl,
    fa(np:nb,
     t(np:nb/n,a,a,'DT','O','O'),
     t(n,woman,woman,'NN','O','O')),
    fa(s:dcl\np,
     t((s:dcl\np)/ (s:ng\np),is,be,'VBZ','O','O'),
     t(s:ng\np,sleeping,sleep,'VBG','O','O')))))).

ccg(98,
 ba(s:dcl,
  fa(np:nb,
   t(np:nb/n,'Every','Every','DT','O','O'),
   t(n,man,man,'NN','O','O')),
  fa(s:dcl\np,
   t((s:dcl\np)/ (s:ng\np),is,be,'VBZ','O','O'),
   ba(s:ng\np,
    fa(s:ng\np,
     t((s:ng\np)/np,eating,eat,'VBG','O','O'),
     fa(np:nb,
      t(np:nb/n,every,every,'DT','O','O'),
      t(n,apple,apple,'NN','O','O'))),
    conj((s:ng\np)\ (s:ng\np), s:ng\np,
     t(conj,and,and,'CC','O','O'),
     fa(s:ng\np,
      t((s:ng\np)/np,watching,watch,'VBG','O','O'),
      fa(np:nb,
       t(np:nb/n,some,some,'DT','O','O'),
       t(n,movie,movie,'NN','O','O')))))))).

ccg(99,
 ba(s:dcl,
  fa(np:nb,
   t(np:nb/n,'All','All','DT','O','O'),
   t(n,men,man,'NNS','O','O')),
  fa(s:dcl\np,
   t((s:dcl\np)/ (s:ng\np),are,be,'VBP','O','O'),
   ba(s:ng\np,
    fa(s:ng\np,
     t((s:ng\np)/np,eating,eat,'VBG','O','O'),
     fa(np:nb,
      t(np:nb/n,all,all,'DT','O','O'),
      t(n,apples,apple,'NNS','O','O'))),
    conj((s:ng\np)\ (s:ng\np), s:ng\np,
     t(conj,and,and,'CC','O','O'),
     fa(s:ng\np,
      t((s:ng\np)/np,watching,watch,'VBG','O','O'),
      fa(np:nb,
       t(np:nb/n,some,some,'DT','O','O'),
       t(n,film,film,'NN','O','O')))))))).

ccg(100,
 ba(s:dcl,
  ba(np:nb,
   fa(np:nb,
    t(np:nb/n,'Every','Every','DT','O','O'),
    t(n,man,man,'NN','O','O')),
   fa(np\np,
    t((np\np)/ (s:dcl\np),who,who,'WP','O','O'),
    fa(s:dcl\np,
     t((s:dcl\np)/np,ate,eat,'VBD','O','O'),
     fa(np:nb,
      t(np:nb/n,a,a,'DT','O','O'),
      t(n,burger,burger,'NN','O','O'))))),
  t(s:dcl\np,died,die,'VBD','O','O'))).

ccg(101,
 ba(s:dcl,
  ba(np:nb,
   fa(np:nb,
    t(np:nb/n,'Every','Every','DT','O','O'),
    fa(n,
     t(n/n,old,old,'JJ','O','O'),
     t(n,man,man,'NN','O','O'))),
   fa(np\np,
    t((np\np)/ (s:dcl\np),which,which,'WDT','O','O'),
    fa(s:dcl\np,
     t((s:dcl\np)/np,ate,eat,'VBD','O','O'),
     fa(np:nb,
      t(np:nb/n,a,a,'DT','O','O'),
      fa(n,
       t(n/n,stale,stale,'JJ','O','O'),
       t(n,burger,burger,'NN','O','O')))))),
  t(s:dcl\np,died,die,'VBD','O','O'))).

ccg(102,
 ba(s:dcl,
  ba(np,
   t(np,'Everybody','Everybody','DT','O','O'),
   fa(np\np,
    t((np\np)/np,in,in,'IN','O','O'),
    fa(np:nb,
     t(np:nb/n,a,a,'DT','O','O'),
     t(n,pub,pub,'NN','O','O')))),
  fa(s:dcl\np,
   t((s:dcl\np)/ (s:adj\np),is,be,'VBZ','O','O'),
   t(s:adj\np,drunk,drunk,'JJ','O','O')))).

ccg(103,
 ba(s:dcl,
  ba(np:nb,
   fa(np:nb,
    t(np:nb/n,'Every','Every','DT','O','O'),
    t(n,man,man,'NN','O','O')),
   fa(np\np,
    t((np\np)/np,in,in,'IN','O','O'),
    fa(np:nb,
     t(np:nb/n,a,a,'DT','O','O'),
     t(n,pub,pub,'NN','O','O')))),
  fa(s:dcl\np,
   t((s:dcl\np)/ (s:adj\np),is,be,'VBZ','O','O'),
   t(s:adj\np,drunk,drunk,'JJ','O','O')))).

ccg(104,
 fa(s:dcl,
  t(s/s,'Yesterday','Yesterday','NN','O','I-DAT'),
  fa(s:dcl,
   t(s/s,at,at,'IN','O','O'),
   ba(s:dcl,
    lx(np, n,
     fa(n,
      t(n/n,midnight,midnight,'NN','O','I-TIM'),
      t(n,'John','John','NNP','O','I-PER'))),
    ba(s:dcl\np,
     ba(s:dcl\np,
      t(s:dcl\np,danced,dance,'VBD','O','O'),
      t((s\np)\ (s\np),deliberately,deliberately,'RB','O','O')),
     fa((s\np)\ (s\np),
      t(((s\np)\ (s\np))/np,in,in,'IN','O','O'),
      lx(np, n,
       t(n,'Tilburg','Tilburg','NNP','O','I-LOC')))))))).

ccg(105,
 fa(s:dcl,
  t(s/s,'Yesterday','Yesterday','NN','O','I-DAT'),
  ba(s:dcl,
   lx(np, n,
    t(n,'John','John','NNP','O','I-PER')),
   ba(s:dcl\np,
    ba(s:dcl\np,
     fa(s:dcl\np,
      t((s\np)/ (s\np),deliberately,deliberately,'RB','O','O'),
      t(s:dcl\np,danced,dance,'VBD','O','O')),
     fa((s\np)\ (s\np),
      t(((s\np)\ (s\np))/np,in,in,'IN','O','O'),
      lx(np, n,
       t(n,'Tilburg','Tilburg','NNP','O','I-LOC')))),
    fa((s\np)\ (s\np),
     t(((s\np)\ (s\np))/np,at,at,'IN','O','O'),
     lx(np, n,
      t(n,midnight,midnight,'NN','O','I-TIM'))))))).

ccg(106,
 ba(s:dcl,
  lx(np, n,
   t(n,'John','John','NNP','O','I-PER')),
  ba(s:dcl\np,
   ba(s:dcl\np,
    fa(s:dcl\np,
     t((s\np)/ (s\np),deliberately,deliberately,'RB','O','O'),
     t(s:dcl\np,danced,dance,'VBD','O','O')),
    fa((s\np)\ (s\np),
     t(((s\np)\ (s\np))/np,in,in,'IN','O','O'),
     lx(np, n,
      t(n,'Tilburg','Tilburg','NNP','O','I-LOC')))),
   fa((s\np)\ (s\np),
    t(((s\np)\ (s\np))/np,at,at,'IN','O','O'),
    lx(np, n,
     t(n,midnight,midnight,'NN','O','I-TIM')))))).

ccg(107,
 ba(s:dcl,
  lx(np, n,
   t(n,'John','John','NNP','O','I-PER')),
  ba(s:dcl\np,
   ba(s:dcl\np,
    t(s:dcl\np,danced,dance,'VBD','O','O'),
    t((s\np)\ (s\np),deliberately,deliberately,'RB','O','O')),
   fa((s\np)\ (s\np),
    t(((s\np)\ (s\np))/np,at,at,'IN','O','O'),
    ba(np,
     lx(np, n,
      t(n,midnight,midnight,'NN','O','I-TIM')),
     fa(np\np,
      t((np\np)/np,in,in,'IN','O','O'),
      lx(np, n,
       t(n,'Tilburg','Tilburg','NNP','O','I-LOC')))))))).

ccg(108,
 ba(s:dcl,
  lx(np, n,
   t(n,'John','John','NNP','O','I-PER')),
  fa(s:dcl\np,
   bxc((s:dcl\np)/ (s:adj\np),
    t((s:dcl\np)/ (s:adj\np),is,be,'VBZ','O','O'),
    t((s\np)\ (s\np),not,not,'RB','O','O')),
   t(s:adj\np,there,there,'RB','O','O')))).

ccg(109,
 ba(s:dcl,
  t(np:thr,'There','There','EX','O','O'),
  fa(s:dcl\np:thr,
   bxc((s:dcl\np:thr)/np,
    t((s:dcl\np:thr)/np,is,be,'VBZ','O','O'),
    t((s\np)\ (s\np),not,not,'RB','O','O')),
   lx(np, n,
    t(n,'John','John','NNP','O','I-PER'))))).

ccg(110,
 ba(s:dcl,
  t(np:thr,'There','There','EX','O','O'),
  fa(s:dcl\np:thr,
   t((s:dcl\np:thr)/np,is,be,'VBZ','O','O'),
   ba(np:nb,
    fa(np:nb,
     t(np:nb/n,the,the,'DT','O','O'),
     t(n,dog,dog,'NN','O','O')),
    lx(np\np, s:ng\np,
     fa(s:ng\np,
      t((s:ng\np)/np,eating,eat,'VBG','O','O'),
      fa(np:nb,
       t(np:nb/n,a,a,'DT','O','O'),
       t(n,bone,bone,'NN','O','O')))))))).

ccg(111,
 ba(s:dcl,
  fa(np:nb,
   t(np:nb/n,'The','The','DT','O','O'),
   t(n,dog,dog,'NN','O','O')),
  ba(s:dcl\np,
   t(s:dcl\np,is,be,'VBZ','O','O'),
   t((s\np)\ (s\np),there,there,'RB','O','O')))).

ccg(112,
 ba(s:dcl,
  fa(np:nb,
   t(np:nb/n,'The','The','DT','O','O'),
   t(n,boy,boy,'NN','O','O')),
  fa(s:dcl\np,
   t((s:dcl\np)/ (s:ng\np),is,be,'VBZ','O','O'),
   t(s:ng\np,running,run,'VBG','O','O')))).

ccg(113,
 ba(s:dcl,
  fa(np:nb,
   t(np:nb/n,'The','The','DT','O','O'),
   fa(n,
    t(n/n,young,young,'JJ','O','O'),
    t(n,boy,boy,'NN','O','O'))),
  fa(s:dcl\np,
   t((s:dcl\np)/ (s:ng\np),is,be,'VBZ','O','O'),
   t(s:ng\np,running,run,'VBG','O','O')))).

ccg(114,
 ba(s:dcl,
  fa(np:nb,
   t(np:nb/n,'The','The','DT','O','O'),
   fa(n,
    t(n/n,young,young,'JJ','O','O'),
    t(n,boy,boy,'NN','O','O'))),
  fa(s:dcl\np,
   t((s:dcl\np)/ (s:ng\np),is,be,'VBZ','O','O'),
   t(s:ng\np,running,run,'VBG','O','O')))).

ccg(115,
 ba(s:dcl,
  fa(np:nb,
   t(np:nb/n,'The','The','DT','O','O'),
   t(n,boy,boy,'NN','O','O')),
  fa(s:dcl\np,
   t((s:dcl\np)/ (s:ng\np),is,be,'VBZ','O','O'),
   t(s:ng\np,running,run,'VBG','O','O')))).

ccg(116,
 ba(s:dcl,
  fa(np:nb,
   t(np:nb/n,'The','The','DT','O','O'),
   t(n,animal,animal,'NN','O','O')),
  fa(s:dcl\np,
   t((s:dcl\np)/ (s:ng\np),is,be,'VBZ','O','O'),
   t(s:ng\np,running,run,'VBG','O','O')))).

ccg(117,
 ba(s:dcl,
  fa(np:nb,
   t(np:nb/n,'The','The','DT','O','O'),
   t(n,dog,dog,'NN','O','O')),
  fa(s:dcl\np,
   t((s:dcl\np)/ (s:ng\np),is,be,'VBZ','O','O'),
   t(s:ng\np,running,run,'VBG','O','O')))).

ccg(118,
 ba(s:dcl,
  fa(np:nb,
   t(np:nb/n,'The','The','DT','O','O'),
   t(n,dog,dog,'NN','O','O')),
  fa(s:dcl\np,
   t((s:dcl\np)/ (s:ng\np),is,be,'VBZ','O','O'),
   t(s:ng\np,running,run,'VBG','O','O')))).

ccg(119,
 ba(s:dcl,
  fa(np:nb,
   t(np:nb/n,'The','The','DT','O','O'),
   t(n,animal,animal,'NN','O','O')),
  fa(s:dcl\np,
   t((s:dcl\np)/ (s:ng\np),is,be,'VBZ','O','O'),
   t(s:ng\np,running,run,'VBG','O','O')))).

ccg(120,
 ba(s:dcl,
  fa(np:nb,
   t(np:nb/n,'A','A','DT','O','O'),
   t(n,dog,dog,'NN','O','O')),
  fa(s:dcl\np,
   t((s:dcl\np)/ (s:ng\np),is,be,'VBZ','O','O'),
   t(s:ng\np,running,run,'VBG','O','O')))).

ccg(121,
 ba(s:dcl,
  fa(np:nb,
   t(np:nb/n,'The','The','DT','O','O'),
   t(n,animal,animal,'NN','O','O')),
  fa(s:dcl\np,
   t((s:dcl\np)/ (s:ng\np),is,be,'VBZ','O','O'),
   t(s:ng\np,running,run,'VBG','O','O')))).

ccg(122,
 ba(s:dcl,
  fa(np:nb,
   t(np:nb/n,'A','A','DT','O','O'),
   t(n,dog,dog,'NN','O','O')),
  fa(s:dcl\np,
   t((s:dcl\np)/ (s:ng\np),is,be,'VBZ','O','O'),
   t(s:ng\np,running,run,'VBG','O','O')))).

ccg(123,
 ba(s:dcl,
  fa(np:nb,
   t(np:nb/n,'The','The','DT','O','O'),
   fa(n,
    t(n/n,black,black,'JJ','O','O'),
    t(n,dog,dog,'NN','O','O'))),
  fa(s:dcl\np,
   t((s:dcl\np)/ (s:ng\np),is,be,'VBZ','O','O'),
   t(s:ng\np,running,run,'VBG','O','O')))).

ccg(124,
 ba(s:dcl,
  lx(np, n,
   t(n,'Mary','Mary','NNP','O','I-PER')),
  ba(s:dcl\np,
   ba(s:dcl\np,
    fa(s:dcl\np,
     t((s\np)/ (s\np),deliberately,deliberately,'RB','O','O'),
     fa(s:dcl\np,
      t((s:dcl\np)/np,punched,punch,'VBD','O','O'),
      lx(np, n,
       t(n,'John','John','NNP','O','I-PER')))),
    t((s\np)\ (s\np),yesterday,yesterday,'NN','O','I-DAT')),
   fa((s\np)\ (s\np),
    t(((s\np)\ (s\np))/np,in,in,'IN','O','O'),
    fa(np:nb,
     t(np:nb/n,the,the,'DT','O','O'),
     t(n,face,face,'NN','O','O')))))).

ccg(125,
 ba(s:dcl,
  lx(np, n,
   t(n,'Mary','Mary','NNP','O','I-PER')),
  ba(s:dcl\np,
   ba(s:dcl\np,
    fa(s:dcl\np,
     t((s\np)/ (s\np),deliberately,deliberately,'RB','O','O'),
     fa(s:dcl\np,
      t((s:dcl\np)/np,punched,punch,'VBD','O','O'),
      lx(np, n,
       t(n,'John','John','NNP','O','I-PER')))),
    fa((s\np)\ (s\np),
     t(((s\np)\ (s\np))/np,in,in,'IN','O','O'),
     fa(np:nb,
      t(np:nb/n,the,the,'DT','O','O'),
      t(n,face,face,'NN','O','O')))),
   t((s\np)\ (s\np),yesterday,yesterday,'NN','O','I-DAT')))).

ccg(126,
 ba(s:dcl,
  lx(np, n,
   t(n,'Mary','Mary','NNP','O','I-PER')),
  ba(s:dcl\np,
   ba(s:dcl\np,
    fa(s:dcl\np,
     t((s\np)/ (s\np),deliberately,deliberately,'RB','O','O'),
     fa(s:dcl\np,
      t((s:dcl\np)/np,punched,punch,'VBD','O','O'),
      lx(np, n,
       t(n,'John','John','NNP','O','I-PER')))),
    fa((s\np)\ (s\np),
     t(((s\np)\ (s\np))/np,in,in,'IN','O','O'),
     fa(np:nb,
      t(np:nb/n,the,the,'DT','O','O'),
      t(n,face,face,'NN','O','O')))),
   t((s\np)\ (s\np),yesterday,yesterday,'NN','O','I-DAT')))).

ccg(127,
 fa(s:dcl,
  t(s/s,'Yesterday','Yesterday','NN','O','I-DAT'),
  ba(s:dcl,
   lx(np, n,
    t(n,'Mary','Mary','NNP','O','I-PER')),
   fa(s:dcl\np,
    t((s\np)/ (s\np),deliberately,deliberately,'RB','O','O'),
    fa(s:dcl\np,
     t((s:dcl\np)/np,punched,punch,'VBD','O','O'),
     ba(np,
      lx(np, n,
       t(n,'John','John','NNP','O','I-PER')),
      fa(np\np,
       t((np\np)/np,in,in,'IN','O','O'),
       fa(np:nb,
        t(np:nb/n,the,the,'DT','O','O'),
        t(n,face,face,'NN','O','O'))))))))).

ccg(128,
 fa(s:dcl,
  t(s/s,'Yesterday','Yesterday','NN','O','I-DAT'),
  ba(s:dcl,
   lx(np, n,
    t(n,'Mary','Mary','NNP','O','I-PER')),
   fa(s:dcl\np,
    t((s\np)/ (s\np),deliberately,deliberately,'RB','O','O'),
    fa(s:dcl\np,
     t((s:dcl\np)/np,punched,punch,'VBD','O','O'),
     ba(np,
      lx(np, n,
       t(n,'John','John','NNP','O','I-PER')),
      fa(np\np,
       t((np\np)/np,in,in,'IN','O','O'),
       fa(np:nb,
        t(np:nb/n,the,the,'DT','O','O'),
        t(n,face,face,'NN','O','O'))))))))).

ccg(129,
 ba(s:dcl,
  lx(np, n,
   t(n,'Mary','Mary','NNP','O','I-PER')),
  ba(s:dcl\np,
   ba(s:dcl\np,
    ba(s:dcl\np,
     fa(s:dcl\np,
      t((s:dcl\np)/np,punched,punch,'VBD','O','O'),
      lx(np, n,
       t(n,'John','John','NNP','O','I-PER'))),
     t((s\np)\ (s\np),deliberately,deliberately,'RB','O','O')),
    fa((s\np)\ (s\np),
     t(((s\np)\ (s\np))/np,in,in,'IN','O','O'),
     fa(np:nb,
      t(np:nb/n,the,the,'DT','O','O'),
      t(n,face,face,'NN','O','O')))),
   t((s\np)\ (s\np),yesterday,yesterday,'NN','O','I-DAT')))).

ccg(130,
 ba(s:dcl,
  lx(np, n,
   t(n,'Mary','Mary','NNP','O','I-PER')),
  ba(s:dcl\np,
   ba(s:dcl\np,
    ba(s:dcl\np,
     fa(s:dcl\np,
      t((s:dcl\np)/np,punched,punch,'VBD','O','O'),
      lx(np, n,
       t(n,'John','John','NNP','O','I-PER'))),
     t((s\np)\ (s\np),deliberately,deliberately,'RB','O','O')),
    fa((s\np)\ (s\np),
     t(((s\np)\ (s\np))/np,in,in,'IN','O','O'),
     fa(np:nb,
      t(np:nb/n,the,the,'DT','O','O'),
      t(n,face,face,'NN','O','O')))),
   t((s\np)\ (s\np),yesterday,yesterday,'NN','O','I-DAT')))).

ccg(131,
 fa(s:dcl,
  t(s/s,'Yesterday','Yesterday','NN','O','I-DAT'),
  ba(s:dcl,
   lx(np, n,
    t(n,'Mary','Mary','NNP','O','I-PER')),
   ba(s:dcl\np,
    ba(s:dcl\np,
     fa(s:dcl\np,
      t((s:dcl\np)/np,punched,punch,'VBD','O','O'),
      lx(np, n,
       t(n,'John','John','NNP','O','I-PER'))),
     t((s\np)\ (s\np),deliberately,deliberately,'RB','O','O')),
    fa((s\np)\ (s\np),
     t(((s\np)\ (s\np))/np,in,in,'IN','O','O'),
     fa(np:nb,
      t(np:nb/n,the,the,'DT','O','O'),
      t(n,face,face,'NN','O','O'))))))).

ccg(132,
 fa(s:dcl,
  t(s/s,'Yesterday','Yesterday','NN','O','I-DAT'),
  ba(s:dcl,
   lx(np, n,
    t(n,'Mary','Mary','NNP','O','I-PER')),
   ba(s:dcl\np,
    ba(s:dcl\np,
     fa(s:dcl\np,
      t((s:dcl\np)/np,punched,punch,'VBD','O','O'),
      lx(np, n,
       t(n,'John','John','NNP','O','I-PER'))),
     t((s\np)\ (s\np),deliberately,deliberately,'RB','O','O')),
    fa((s\np)\ (s\np),
     t(((s\np)\ (s\np))/np,in,in,'IN','O','O'),
     fa(np:nb,
      t(np:nb/n,the,the,'DT','O','O'),
      t(n,face,face,'NN','O','O'))))))).

ccg(133,
 ba(s:dcl,
  lx(np, n,
   t(n,'Mary','Mary','NNP','O','I-PER')),
  ba(s:dcl\np,
   ba(s:dcl\np,
    fa(s:dcl\np,
     t((s\np)/ (s\np),deliberately,deliberately,'RB','O','O'),
     fa(s:dcl\np,
      t((s:dcl\np)/np,punched,punch,'VBD','O','O'),
      lx(np, n,
       t(n,'John','John','NNP','O','I-PER')))),
    t((s\np)\ (s\np),yesterday,yesterday,'NN','O','I-DAT')),
   fa((s\np)\ (s\np),
    t(((s\np)\ (s\np))/np,in,in,'IN','O','O'),
    fa(np:nb,
     t(np:nb/n,the,the,'DT','O','O'),
     t(n,face,face,'NN','O','O')))))).

ccg(134,
 ba(s:dcl,
  lx(np, n,
   t(n,'Mary','Mary','NNP','O','I-PER')),
  ba(s:dcl\np,
   ba(s:dcl\np,
    ba(s:dcl\np,
     fa(s:dcl\np,
      t((s:dcl\np)/np,punched,punch,'VBD','O','O'),
      lx(np, n,
       t(n,'John','John','NNP','O','I-PER'))),
     t((s\np)\ (s\np),deliberately,deliberately,'RB','O','O')),
    fa((s\np)\ (s\np),
     t(((s\np)\ (s\np))/np,in,in,'IN','O','O'),
     fa(np:nb,
      t(np:nb/n,the,the,'DT','O','O'),
      t(n,face,face,'NN','O','O')))),
   t((s\np)\ (s\np),yesterday,yesterday,'NN','O','I-DAT')))).

ccg(135,
 ba(s:dcl,
  lx(np, n,
   t(n,'Mary','Mary','NNP','O','I-PER')),
  ba(s:dcl\np,
   ba(s:dcl\np,
    fa(s:dcl\np,
     t((s\np)/ (s\np),deliberately,deliberately,'RB','O','O'),
     fa(s:dcl\np,
      t((s:dcl\np)/np,punched,punch,'VBD','O','O'),
      lx(np, n,
       t(n,'John','John','NNP','O','I-PER')))),
    t((s\np)\ (s\np),yesterday,yesterday,'NN','O','I-DAT')),
   fa((s\np)\ (s\np),
    t(((s\np)\ (s\np))/np,in,in,'IN','O','O'),
    fa(np:nb,
     t(np:nb/n,the,the,'DT','O','O'),
     t(n,face,face,'NN','O','O')))))).

